Repository WordPress/openverse-frontend, pull requests merged in 2021-10, with the labels that each got.

#282 Update i18n locales in `valid-locales.json`
  src/locales/scripts/valid-locales.json
Labels: 🧰 goal: internal improvement, ♿️ aspect: a11y

#287 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#279 Remove references to api.creativecommons.engineering
  README.md
  src/data/usage-data-service.js
Labels: 🛠 goal: fix, 📄 aspect: text

#278 Fix 'scroll to top' button
  src/components/ScrollButton.vue
  tailwind.config.js
Labels: 🛠 goal: fix, 🕹 aspect: interface

#290 Fix Windows full path in .pot file
  src/locales/scripts/parse-vue-files.js
Labels: 🛠 goal: fix, 💻 aspect: code

#245 Define functionality for the `AudioThumbnail` component
  src/components/AudioThumbnail/AudioThumbnail.vue
  src/components/AudioThumbnail/meta/AudioThumbnail.stories.mdx
  src/components/AudioTrack/AudioThumbnail.vue
  src/components/AudioTrack/layouts/Row.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: 🌟 goal: addition, 💻 aspect: code

#284 Use related composable
  src/components/AudioDetails/Related.vue
  src/components/ImageDetails/RelatedImages.vue
  src/components/RelatedImages.vue
  src/composables/use-related.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/photos/_id.vue
  src/store/related.js
  test/unit/specs/components/related-audios.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/store/related-media-store.spec.js
Labels: 🛠 goal: fix, 💻 aspect: code

#293 Add `cross-env` dependency
  package-lock.json
  package.json
Labels: 🛠 goal: fix, 🤖 aspect: dx

#243 Fix licence information flyout menu alignment
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/LicenseExplanationTooltip.vue
Labels: 🛠 goal: fix, 🕹 aspect: interface

#297 Update Dockerfile node/npm version and add translations
  Dockerfile
Labels: ✨ goal: improvement, 🤖 aspect: dx

#295 Add contribution guideline about JSDoc types
  CONTRIBUTING.md
Labels: 🌟 goal: addition, 📄 aspect: text

#384 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx
