Repository WordPress/openverse-frontend, pull requests merged in 2021-08, with the labels that each got.

#114 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#124 Speed up pre-commit hooks
  .husky/pre-commit
  .lintstagedrc
  package-lock.json
  package.json
Labels: 🤖 aspect: dx

#123 Add images of empowerment to meta search
  src/utils/getLegacySourceUrl.js
Labels: 🌟 goal: addition, 💻 aspect: code

#133 Audio track + waveform A11y
  src/components/AudioTrack/AudioTrack.vue
  src/components/AudioTrack/PlayPause.vue
  src/components/AudioTrack/Waveform.vue
  src/components/AudioTrack/meta/AudioTrack.stories.mdx
  src/locales/en.json
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface
