Repository WordPress/openverse-frontend, pull requests merged in 2021-09, with the labels that each got.

#208 Remove unused code
  src/components/SearchGridManualLoad.vue
  src/styles/utilities/initial-variables.scss
Labels: bug, 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#211 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#214 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#224 Fix dropdowns and icons
  src/assets/fonts.css
  src/components/Dropdown.vue
  src/styles/components/navbar.sass
  src/styles/utilities/icon-font.scss
  src/styles/utilities/initial-variables.scss
  src/styles/vocabulary.scss
Labels: 🛠 goal: fix, 🕹 aspect: interface

#212 Show a CC Search → Openverse notice
  nuxt.config.js
  src/components/MigrationNotice.vue
  src/components/NoticeBar/NoticeBar.vue
  src/components/NoticeBar/meta/NoticeBar.stories.mdx
  src/layouts/embedded-with-nav-search.vue
  src/layouts/embedded.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/middleware/middleware.js
  src/plugins/migration-notice.js
  src/plugins/url-change.js
  src/store-modules/mutation-types.js
  src/store-modules/nav-store.js
  tailwind.config.js
Labels: 🌟 goal: addition, 💻 aspect: code

#231 Transfer `CODEBASE.md` to handbook
  CODEBASE.md
  README.md
Labels: ✨ goal: improvement, 📄 aspect: text

#232 Make the link to the handbook absolute
  README.md
Labels: documentation, 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#233 Add title bottom spacing
  src/pages/search-help.vue
Labels: 🛠 goal: fix, 🕹 aspect: interface

#207 Active Media Vuex Model + Composable AudioTrack
  src/assets/licenses/by.svg
  src/assets/licenses/cc-logo.svg
  src/assets/licenses/cc0.svg
  src/assets/licenses/nc.svg
  src/assets/licenses/nd.svg
  src/assets/licenses/pdm.svg
  src/assets/licenses/sa.svg
  src/components/AudioTrack/AudioController.vue
  src/components/AudioTrack/AudioThumbnail.vue
  src/components/AudioTrack/AudioTrack.vue
  src/components/AudioTrack/PlayPause.vue
  src/components/AudioTrack/Waveform.vue
  src/components/AudioTrack/layouts/Full.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/AudioTrack/meta/AudioTrack.stories.mdx
  src/components/AudioTrack/meta/PlayPause.stories.mdx
  src/components/License/License.vue
  src/components/License/meta/License.stories.mdx
  src/constants/license.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/store-modules/active-media-store.js
  src/store-modules/mutation-types.js
  src/store-modules/types.d.ts
  src/store/index.js
  src/styles/base/generic.sass
  tailwind.config.js
Labels: 🌟 goal: addition, 💻 aspect: code

#234 Fix the API link in the "Resources" menu dropdown.
  src/components/EmbeddedNavSection.vue
  src/components/NavSection.vue
Labels: 🛠 goal: fix, 🕹 aspect: interface

#235 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#240 Add feature flag for non-image media types
  nuxt.config.js
  src/components/HeroSection.vue
  src/components/SearchTypeTabs.vue
  src/pages/search/audio.vue
  src/store-modules/filter-store.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#174 Single result page for audio
  nuxt.config.js
  src/components/AudioDetails/Related.vue
  src/components/AudioDetails/Table.vue
  src/components/AudioDetails/Tags.vue
  src/components/AudioTrack/AudioThumbnail.vue
  src/components/MediaInfo/CopyLicense.vue
  src/components/MediaInfo/MediaReuse.vue
  src/components/ScrollButton.vue
  src/data/sample-audio-responses.json
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/store-modules/action-types.js
  src/store-modules/mutation-types.js
  src/store-modules/related-media-store.js
  src/store-modules/search-store.js
  src/store-modules/types.d.ts
  src/utils/sixpack.js
  test/unit/specs/store/search-store.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#249 Fix typo on WordPress word
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: 🛠 goal: fix, 📄 aspect: text

#251 Fix paths for jest coverage
  jest.config.js
Labels: 🛠 goal: fix, 🤖 aspect: dx

#252 Update URL ref parameter values for analytics
  src/components/Filters/LicenseExplanationTooltip.vue
Labels: 🛠 goal: fix, 💻 aspect: code

#253 Updated URL ref parameter values for analytics for PhotoDetails.vue
  src/components/ImageDetails/PhotoDetails.vue
Labels: 💻 aspect: code, 🧰 goal: internal improvement

#255 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#259 Fix license icon spacing
  src/components/License/License.vue
Labels: ✨ goal: improvement, 🕹 aspect: interface

#257 Linting and formatting hotfixes for AudioTrack Row
  src/components/AudioTrack/layouts/Row.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/styles/utilities/icon-font.scss
Labels: 🛠 goal: fix, 💻 aspect: code

#261 Switch to extracted comments in `openverse.pot`, remove duplicated context
  src/locales/po-files/openverse.pot
  src/locales/scripts/json-to-pot.js
Labels: 🛠 goal: fix, ♿️ aspect: a11y

#264 Put the creator of the track on a new line
  src/components/AudioTrack/layouts/Full.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: ✨ goal: improvement, 🕹 aspect: interface

#267 Cookie policies for iframe usage
  nuxt.config.js
  src/utils/session-id.js
Labels: 🛠 goal: fix, ♿️ aspect: a11y

#268 🔄 Synced file(s) with WordPress/openverse
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠 goal: fix, 🤖 aspect: dx

#262 Url camelcase fix
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/MediaInfo/CopyLicense.vue
  src/components/MediaInfo/MediaLicense.vue
  src/components/MediaInfo/MediaReuse.vue
  src/pages/audio/_id.vue
  src/utils/attribution-html.js
  test/unit/specs/components/ImageDetails/copy-license.spec.js
  test/unit/specs/components/ImageDetails/image-attribution.spec.js
  test/unit/specs/components/ImageDetails/image-info.spec.js
Labels: 🛠 goal: fix, 💻 aspect: code

#213 Add DownloadButton component
  package-lock.json
  package.json
  src/components/DownloadButton.vue
  src/components/DropdownButton.vue
  src/components/meta/DownloadButton.stories.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/unit/specs/components/download-button.spec.js
  test/unit/test-utils/render.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#239 Change AudioTrack component according to filters sidebar
  .gitignore
  package.json
  src/components/AudioResultsList.vue
  src/components/AudioTrack/layouts/Full.vue
  src/components/AudioTrack/layouts/Row.vue
  src/locales/po-files/openverse.pot
  tailwind.config.js
  test/unit/specs/components/AudioTrack/audio-track.spec.js
Labels: 🛠 goal: fix, 🕹 aspect: interface

#276 remove social share + fix default flags
  nuxt.config.js
  package.json
  src/analytics/events.js
  src/components/HeroSection.vue
  src/components/ImageDetails/ImageSocialShare.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/SocialShareButtons.vue
  src/components/SearchTypeTabs.vue
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/constants/usage-data-analytics-types.js
  src/feature-flags/index.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/photos/_id.vue
  src/pages/search/audio.vue
  src/store-modules/filter-store.js
  src/store/social.js
  test/unit/specs/components/ImageDetails/image-social-share.spec.js
  test/unit/specs/components/ImageDetails/photo-details.spec.js
  test/unit/specs/components/ImageDetails/social-share-buttons.spec.js
  test/unit/specs/store/social-store.spec.js
Labels: 🛠 goal: fix, 🤖 aspect: dx

#272 Remove button styling from "no results" text
  src/components/MetaSearch/MetaSearchForm.vue
  src/components/SearchGridManualLoad.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search/audio.vue
  src/pages/search/video.vue
Labels: 🛠 goal: fix, 🕹 aspect: interface
