Repository WordPress/openverse-frontend, pull requests merged in 2021-12, with the labels that each got.

#456 Make single result page for images RTL-compatible
  src/components/CopyButton.vue
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/LegalDisclaimer.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/RelatedImages.vue
  src/components/ImageGrid/ImageCell.vue
  src/components/ImageGrid/ImageGrid.vue
  src/components/LicenseElements.vue
  src/components/MediaInfo/CopyLicense.vue
  src/components/MediaInfo/MediaLicense.vue
  src/components/PhotoTags.vue
  src/components/SearchGridCell.vue
  src/styles/components/tabs.scss
  src/styles/photodetails.scss
  src/utils/get-provider-logo.js
  test/unit/specs/components/ImageDetails/photo-details.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#467 Add /healthcheck endpoint
  nuxt.config.js
  src/server-middleware/healthcheck.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#461 Set default English locale correctly
  nuxt.config.js
  src/mixins/i18n-sync.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#452 Safelist the classes for common icon sizes
  src/components/VIcon/VIcon.vue
  tailwind.config.js
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#432 Simplify Filter Sidebar component and improve scrollbar styles
  src/components/Filters/FiltersList.vue
  src/components/Filters/SearchGridFilter.vue
  src/components/VCheckbox.vue
  tailwind.config.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#471 Fix button ring offset
  src/components/VButton.vue
  tailwind.config.js
Labels: 🟩 priority: low, 🛠 goal: fix, ♿️ aspect: a11y

#448 VLogoLoader
  src/components/VLogoLoader/VLogoLoader.types.js
  src/components/VLogoLoader/VLogoLoader.vue
  src/components/VLogoLoader/meta/VLogoLoader.stories.js
  src/composables/use-event-listener.js
  src/composables/use-media-query.js
  test/unit/specs/components/v-logo-loader.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#481 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#484 Fix a typo that prevents subsequent fetches to not be decoded
  src/store/media.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#498 Update README.md to remove broken link
  README.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#459 Improve focus styles for audio subcomponents
  src/components/AudioTrack/PlayPause.vue
  src/components/AudioTrack/Waveform.vue
  src/components/AudioTrack/layouts/Full.vue
  src/components/AudioTrack/layouts/Global.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/AudioTrack/meta/PlayPause.stories.mdx
  src/components/Header/SearchBar/SearchButton.vue
  src/components/VIconButton/VIconButton.vue
  src/components/VIconButton/meta/VIconButton.stories.mdx
  src/composables/use-media-query.js
  src/constants/screens.js
  src/pages/search.vue
  tailwind.config.js
  test/unit/specs/components/Header/SearchBar/search-bar.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#473 Add e2e test for image detail page
  .github/workflows-disabled/end-to-end-tests.yml
  src/components/ImageGrid/ImageCell.vue
  src/components/SearchGridCell.vue
  src/pages/image/_id.vue
  test/e2e/homepage.spec.js
  test/e2e/image-detail.spec.js
  test/e2e/search.spec.js
  test/unit/specs/components/ImageDetails/photo-details.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#469 Add Modal component
  package-lock.json
  package.json
  src/components/SaferBrowsing.vue
  src/components/VButton.vue
  src/components/VModal/VModal.vue
  src/components/VModal/VModalContent.vue
  src/components/VModal/VModalTarget.vue
  src/components/VModal/meta/VModal.stories.js
  src/components/VPopover/VPopoverContent.vue
  src/components/VTeleport.js
  src/composables/use-body-scroll-lock.js
  src/composables/use-dialog-content.js
  src/composables/use-focus-on-blur.js
  src/composables/use-focus-on-hide.js
  src/composables/use-focus-on-show.js
  src/composables/use-hide-on-click-outside.js
  src/composables/use-popover-content.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/unit/specs/components/v-modal.spec.js
Labels: 🟩 priority: low, 🚧 status: blocked, 🌟 goal: addition, 🕹 aspect: interface

#492 Redirect on image detail page
  README.md
  nuxt.config.js
  package-lock.json
  package.json
  test/e2e/image-detail.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#497 Add a transform step after receiving data from the API
  src/components/AudioResultsList.vue
  src/data/audio-service.js
  src/data/base-media-service.js
  src/data/image-service.js
  src/pages/search.vue
  src/store/media.js
  test/unit/specs/store/media-store.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#509 Fix API endpoints for related media and provider stats
  src/data/api-service.js
  src/data/audio-service.js
  src/data/existing-audio-providers.js
  src/data/existing-image-providers.js
  src/data/image-service.js
  src/data/media-provider-service.js
  src/pages/sources.vue
  src/store/provider.js
  test/unit/specs/store/media-store.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#517 Add ts-node to stop Storybook complaining about tsconfig.json
  package-lock.json
  package.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#514 Fix audio RTL visual bugs
  src/components/AudioDetails/Tags.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/MediaTag/MediaTag.vue
  test/unit/specs/components/MediaTag/media-tag.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#504 Update AudioTrack layouts as per new designs
  nuxt.config.js
  src/components/AudioTrack/AudioTrack.vue
  src/components/AudioTrack/Waveform.vue
  src/components/AudioTrack/layouts/Box.vue
  src/components/AudioTrack/layouts/Full.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/AudioTrack/meta/AudioTrack.stories.mdx
  src/components/AudioTrack/meta/Waveform.stories.mdx
  src/components/Skeleton/AudioTrackSkeleton.vue
  src/components/Skeleton/VBone.vue
  src/constants/screens.js
  tailwind.config.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#382 Refactor search results components and media fetching
  nuxt.config.js
  src/components/AudioResultsList.vue
  src/components/Filters/FilterDisplay.vue
  src/components/ImageDetails/RelatedImages.vue
  src/components/ImageGrid/ImageGrid.vue
  src/components/ImageGrid/LoadMoreButton.vue
  src/components/SearchGrid.vue
  src/components/SearchGridManualLoad.vue
  src/components/Skeleton/GridSkeleton.vue
  src/components/VHeroSection.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VSaferBrowsing.vue
  src/components/VScrollButton.vue
  src/components/VSearchGrid.vue
  src/components/VSearchRating.vue
  src/composables/use-load-more.js
  src/pages/index.vue
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/pages/search/search-page.types.js
  src/pages/search/video.vue
  src/store/media.js
  src/store/search.js
  src/store/types.d.ts
  src/utils/get-legacy-source-url.js
  test/e2e/content-types.spec.js
  test/e2e/homepage.spec.js
  test/e2e/search.spec.js
  test/unit/specs/components/__snapshots__/filter-display.spec.js.snap
  test/unit/specs/components/hero-section.spec.js
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/scroll-button.spec.js
  test/unit/specs/components/search-grid-wrapper.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/search-rating.spec.js
  test/unit/specs/store/media-store.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#526 Meta Search Provider: The Greats added (ticket #299)
  src/utils/get-legacy-source-url.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#525 Use pnpm (and fix Storybook issues as a result)
  .github/workflows/ci.yml
  .github/workflows/pre-build.yaml
  .husky/pre-commit
  .husky/pre-push
  .npmrc
  .prettierignore
  Dockerfile
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/AudioTrack/meta/AudioTrack.stories.mdx
  src/components/AudioTrack/meta/flac-waveform.json
  src/components/AudioTrack/meta/mp3-waveform.json
  src/components/AudioTrack/meta/ogg-waveform.json
  src/components/AudioTrack/meta/wav-waveform.json
  src/components/VItemGroup/VItemGroup.vue
  src/components/VModal/VModalContent.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.types.js
  src/locales/scripts/README.md
  src/locales/scripts/get-translations.js
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#528 Replace babel-eslint with @babel/eslint-parser
  .eslintrc.js
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#457 Add translation notification banner
  package.json
  pnpm-lock.yaml
  src/components/NotificationBanner.vue
  src/components/TranslationStatusBanner.vue
  src/composables/types.js
  src/composables/use-i18n-sync.js
  src/composables/use-storage.js
  src/layouts/default.vue
  src/layouts/with-nav-search.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/locales/scripts/create-wp-locale-list.js
  src/locales/scripts/get-translations-status.js
  src/locales/scripts/get-translations.js
  src/locales/scripts/get-validated-locales.js
  src/locales/scripts/locales-list.json
  src/locales/scripts/types.d.ts
  src/locales/scripts/untranslated-locales.json
  src/locales/scripts/update-locale-list.js
  src/locales/scripts/wp-locales.json
  src/mixins/i18n-sync.js
  src/store/notification.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#489 Add VFilterButton
  package.json
  pnpm-lock.yaml
  src/assets/icons/filter.svg
  src/components/SearchGridForm.vue
  src/components/VButton.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VFilterDisplay.vue
  src/components/VFilters/VFilterTag.vue
  src/components/VFilters/VLicenseExplanationTooltip.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/README.md
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/meta/VFilterButton.stories.mdx
  src/components/VLogoLoader/VLogoLoader.vue
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-media-query.js
  src/composables/use-window-scroll.js
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/styles/global.scss
  tailwind.config.js
  test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
  test/unit/specs/components/VHeader/v-filter-button.spec.js
  test/unit/specs/components/filter-checklist.spec.js
  test/unit/specs/components/filter-display.spec.js
  test/unit/specs/components/filter-tag.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#537 Fix filters modal position in iframe
  src/components/AppModal.vue
  src/locales/scripts/wp-locales.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#545 Update wp-locales.json
  src/locales/scripts/wp-locales.json
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#540 Upgrade Tailwind to version 3 with JIT mode
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  src/components/SearchGridForm.vue
  src/components/VHeroSection.vue
  src/constants/screens.js
  src/styles/tailwind.css
  tailwind.config.js
  tailwind.safelist.txt
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#520 Add Storybook smoketest to GitHub CI
  .github/workflows/ci.yml
  nuxt.config.js
  src/components/VModal/VModalContent.vue
  src/components/VModal/VModalTarget.vue
  src/components/VTeleport.js
  src/components/VTeleport/README.md
  src/components/VTeleport/VTeleport.vue
  src/components/VTeleport/VTeleportTarget.vue
  src/components/VTeleport/meta/targets.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#531 Allow enabling or disabling interactivity of waveform
  src/components/AudioDetails/Related.vue
  src/components/VAudioTrack/VAudioController.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VAudioTrack/meta/VAudioTrack.stories.mdx
  src/components/VAudioTrack/meta/VPlayPause.stories.mdx
  src/components/VAudioTrack/meta/VWaveform.stories.mdx
  src/components/VAudioTrack/meta/flac-waveform.json
  src/components/VAudioTrack/meta/mp3-waveform.json
  src/components/VAudioTrack/meta/ogg-waveform.json
  src/components/VAudioTrack/meta/wav-waveform.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/search/audio.vue
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/components/related-audios.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#551 Use `extensions` rather than ignore to import components
  nuxt.config.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#547 Stop importing from nuxt.config.js
  nuxt.config.js
  src/composables/use-i18n-sync.js
  src/data/audio-service.js
  src/middleware/middleware.js
  src/mixins/iframe-height.js
  src/plugins/url-change.js
  src/utils/dev.js
  src/utils/env.js
  src/utils/send-message.js
  test/unit/setup.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#553 Remove stray whitespace
  src/components/VMetaSearch/VMetaSearchForm.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#550 Deploy Storybook to GitHub pages
  .github/workflows/gh-pages.yaml
  README.md
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#564 🔄 Synced file(s) with WordPress/openverse
  .github/release-drafter.yml
  .github/workflows-disabled/project-automation.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/pr_ping.yml
  .prettierignore
  docker-compose.yml
  prettier.config.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx
