Repository WordPress/openverse-frontend, pull requests merged in 2021-11, with the labels that each got.

#379 Add a dependencies section and remove the redundant title
  .github/ISSUE_TEMPLATE/component_spec.md
Labels: ✨ goal: improvement, 🤖 aspect: dx

#355 Use Tailwind RTL styles everywhere
  src/components/AppModal.vue
  src/components/AudioDetails/Tags.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/ContentReport/ContentReportForm.vue
  src/components/ContentReport/DmcaNotice.vue
  src/components/ContentReport/OtherIssueForm.vue
  src/components/ContentReport/ReportError.vue
  src/components/CopyButton.vue
  src/components/ExtensionBrowsers.vue
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FilterDisplay.vue
  src/components/Filters/FilterTag.vue
  src/components/Filters/FiltersList.vue
  src/components/FooterSection.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/MetaSearch/MetaSourceList.vue
  src/components/NavSection.vue
  src/components/SaferBrowsing.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/components/SearchTypeToggle.vue
  test/unit/specs/components/__snapshots__/filter-display.spec.js.snap
  test/unit/specs/components/__snapshots__/filter-tag.spec.js.snap
Labels: ✨ goal: improvement, 💻 aspect: code

#372 Add base Button component
  jest.config.js
  package-lock.json
  package.json
  src/components/VButton.vue
  src/components/meta/VButton.stories.js
  src/utils/a11y/get-tab-index.js
  src/utils/a11y/is-native-tabbale.js
  src/utils/a11y/supports-disabled-attribute.js
  tailwind.config.js
  test/unit/specs/components/v-button.spec.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#367 Avoid error using only local translation files
  .github/workflows/ci.yml
  .gitignore
  package.json
  src/locales/scripts/valid-locales.json
Labels: 💻 aspect: code, 🧰 goal: internal improvement

#403 Tailwind breakpoints
  src/components/AppModal.vue
  src/components/AudioResultsList.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/LicenseExplanationTooltip.vue
  src/components/Filters/SearchGridFilter.vue
  src/components/HeroSection.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/pages/audio/_id.vue
  src/pages/search.vue
  tailwind.config.js
  test/unit/specs/components/search-grid-filter.spec.js
Labels: ✨ goal: improvement, 💻 aspect: code

#392 Create Skeleton components
  nuxt.config.js
  src/components/Skeleton/AudioTrackSkeleton.vue
  src/components/Skeleton/GridSkeleton.vue
  src/components/Skeleton/VBone.vue
  src/components/Skeleton/meta/GridSkeleton.stories.mdx
  tailwind.config.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#399 Create a global audio player (amongst many smaller improvements)
  src/assets/icons/close.svg
  src/components/AudioTrack/AudioController.vue
  src/components/AudioTrack/AudioTrack.vue
  src/components/AudioTrack/PlayPause.vue
  src/components/AudioTrack/Waveform.vue
  src/components/AudioTrack/layouts/Full.vue
  src/components/AudioTrack/layouts/Global.vue
  src/components/AudioTrack/layouts/Row.vue
  src/components/AudioTrack/meta/AudioTrack.stories.mdx
  src/components/AudioTrack/meta/PlayPause.stories.mdx
  src/components/AudioTrack/meta/Waveform.stories.mdx
  src/components/License/License.vue
  src/components/VIcon/VIcon.vue
  src/components/VIcon/meta/VIcon.stories.mdx
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/store/active.js
  src/store/types.d.ts
  tailwind.config.js
Labels: 🌟 goal: addition, 💻 aspect: code

#408 Update breakpoints to the new Tailwind config
  src/components/Skeleton/GridSkeleton.vue
Labels: 🛠 goal: fix, 💻 aspect: code

#394 Add playwright e2e tests
  .eslintrc.js
  README.md
  cypress.json
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  nuxt.config.js
  package-lock.json
  package.json
  playwright.config.js
  src/pages/search.vue
  test/e2e/filters.spec.js
  test/e2e/homepage.spec.js
  test/e2e/resources/last_page.json
  test/e2e/resources/mock_data.json
  test/e2e/resources/sample_image.jpg
  test/e2e/search-query-client.spec.js
  test/e2e/search-query-server.spec.js
  test/e2e/search.spec.js
  test/iframe-test.html
Labels: 🌟 goal: addition, 💻 aspect: code

#411 Replace PDM logo
  src/assets/licenses/nc.svg
  src/assets/licenses/pdm.svg
  src/components/AudioTrack/layouts/Row.vue
  src/components/License/VLicense.vue
  src/components/License/meta/VLicense.stories.mdx
  src/constants/license.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#413 Node 16 and NPM 8
  package-lock.json
  package.json
Labels: 💻 aspect: code, 🧰 goal: internal improvement

#398 Search and media store refactoring
  src/components/AudioDetails/Tags.vue
  src/components/AudioResultsList.vue
  src/components/EmbeddedNavSection.vue
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FilterDisplay.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/SearchGridFilter.vue
  src/components/HeroSection.vue
  src/components/HomeLicenseFilter.vue
  src/components/NavSection.vue
  src/components/PhotoTags.vue
  src/components/SaferBrowsing.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/pages/audio/_id.vue
  src/pages/index.vue
  src/pages/photos/_id.vue
  src/pages/search.vue
  src/store/filter.js
  src/store/media.js
  src/store/provider.js
  src/store/search.js
  src/store/types.d.ts
  src/styles/results-page.scss
  src/utils/get-legacy-source-url.js
  src/utils/prepare-search-query-params.js
  src/utils/search-query-transform.js
  test/e2e/homepage.spec.js
  test/e2e/search-query-client.spec.js
  test/unit/specs/components/filter-display.spec.js
  test/unit/specs/components/hero-section.spec.js
  test/unit/specs/components/home-license-filter.spec.js
  test/unit/specs/components/nav-section.spec.js
  test/unit/specs/components/photo-tags.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/search-grid-form.spec.js
  test/unit/specs/components/search-grid-wrapper.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/specs/store/filter-store.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/provider.spec.js
  test/unit/specs/store/search-store.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
  test/unit/test-utils/sample-store.js
Labels: 🛠 goal: fix, 💻 aspect: code

#397 Add VPopover component
  nuxt.config.js
  src/components/.eslintrc.js
  src/components/VButton.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.types.js
  src/components/VPopover/VPopoverContent.vue
  src/components/VPopover/meta/VPopover.stories.js
  src/composables/types.js
  src/composables/use-event-listener-outside.js
  src/composables/use-focus-on-blur.js
  src/composables/use-focus-on-hide.js
  src/composables/use-focus-on-show.js
  src/composables/use-hide-on-click-outside.js
  src/composables/use-popover-content.js
  src/composables/use-popper.js
  src/utils/warn.js
  test/unit/specs/components/v-button.spec.js
  test/unit/specs/components/v-popover.spec.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#380 Create the `InputField` and `SearchBar` components
  .eslintrc.js
  .storybook/decorators/with-rtl.js
  src/assets/icons/search.svg
  src/components/Header/SearchBar/SearchBar.vue
  src/components/Header/SearchBar/SearchButton.vue
  src/components/Header/SearchBar/meta/SearchBar.stories.mdx
  src/components/InputField/InputField.vue
  src/components/InputField/meta/InputField.stories.mdx
  src/locales/en.json
  src/locales/po-files/openverse.pot
  tailwind.config.js
  test/unit/specs/components/Header/SearchBar/search-bar.spec.js
  test/unit/specs/components/InputField/input-field.spec.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#425 Make Homepage RTL-compatible
  src/components/HeroSection.vue
  src/components/HomeLicenseFilter.vue
  src/styles/form/shared.sass
Labels: 🛠 goal: fix, 🕹 aspect: interface

#427 Make Homepage and Searchbar RTL-compatible
  src/components/HeroSection.vue
  src/components/HomeLicenseFilter.vue
  src/components/SaferBrowsing.vue
  src/components/ScrollButton.vue
  src/components/SearchGridForm.vue
  src/styles/form/shared.sass
  src/styles/form/tools.sass
  test/unit/specs/components/search-grid-filter.spec.js
Labels: 🛠 goal: fix, 🕹 aspect: interface

#430 Fix package-lock.json engines
  package-lock.json
Labels: 🛠 goal: fix, 💻 aspect: code

#406 Add Checkbox component
  jest.config.js
  src/assets/icons/checkmark.svg
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/LicenseExplanationTooltip.vue
  src/components/Filters/SearchGridFilter.vue
  src/components/HeroSection.vue
  src/components/HomeLicenseFilter.vue
  src/components/License/VLicense.vue
  src/components/VCheckbox.vue
  src/components/VIcon/VIcon.vue
  src/components/meta/VCheckbox.stories.js
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/pages/index.vue
  src/store/index.js
  src/store/media.js
  src/store/provider.js
  src/store/search.js
  src/styles/base/generic.sass
  src/styles/form/_all.sass
  src/styles/form/radio.sass
  tailwind.config.js
  test/e2e/homepage.spec.js
  test/e2e/search-query-server.spec.js
  test/unit/specs/components/filter-checklist.spec.js
  test/unit/specs/components/hero-section.spec.js
  test/unit/specs/components/home-license-filter.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/v-checkbox.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/search-store.spec.js
Labels: 🌟 goal: addition, 🕹 aspect: interface

#444 Restore husky
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: 🛠 goal: fix, 💻 aspect: code

#404 Removed unused image assets
  src/assets/500px_logo.png
  src/assets/back_arrow.svg
  src/assets/behance_logo.svg
  src/assets/cc-by_icon.svg
  src/assets/cc-cc0_icon.svg
  src/assets/cc-logo_large_black.png
  src/assets/cc-nc_icon.svg
  src/assets/cc-nd_icon.svg
  src/assets/cc-pdm_icon.svg
  src/assets/cc-sa_icon.svg
  src/assets/eol_logo.png
  src/assets/europeana_logo.svg
  src/assets/help_icon.svg
  src/assets/iha_logo.png
  src/assets/jamendo_logo.svg
  src/assets/locale.svg
  src/assets/museumvictoria_logo.svg
  src/assets/nasa_logo.svg
  src/assets/nypl_logo.svg
  src/assets/sciencemuseum_logo.svg
  src/assets/smithsonian_logo.svg
  src/assets/spacex-logo.svg
  src/assets/support.png
Labels: 💻 aspect: code, 🧰 goal: internal improvement

#449 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#429 Make Header RTL-compatible
  src/assets/icons/external-link.svg
  src/components/Dropdown.vue
  src/components/EmbeddedNavSection.vue
  src/components/HeaderSection.vue
  src/components/VIcon/VIcon.vue
  src/components/VIcon/meta/VIcon.stories.mdx
  src/styles/components/navbar.sass
  src/styles/form/input-textarea.sass
  tailwind.config.js
Labels: 🛠 goal: fix, 🕹 aspect: interface

#437 Fix Search form on smaller viewports
  src/components/SearchGridForm.vue
  src/components/VCheckbox.vue
  src/pages/search.vue
Labels: 🛠 goal: fix, 🕹 aspect: interface

#445 SearchGridFilter wrapper component selected based on reactive media query
  src/composables/use-media-query.js
  src/pages/search.vue
  src/utils/get-browser-info.js
  test/unit/setup.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#434 Set explicit ltr direction for pages untranslated in rtl languages
  src/pages/about.vue
  src/pages/extension.vue
  src/pages/feedback.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/sources.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#415 Remove `nuxt-ssr-cache` and move dependencies
  .github/workflows/ci.yml
  nuxt.config.js
  package-lock.json
  package.json
  patches/nuxt-ssr-cache+1.5.2.patch
  src/styles/utilities/functions.scss
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/components/dropdown.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#439 Toggle `SearchGridFilter` completely according to view width
  src/components/ScrollButton.vue
  src/composables/use-media-query.js
  src/pages/search.vue
  src/utils/get-browser-info.js
  test/unit/setup.js
  test/unit/specs/components/scroll-button.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#454 Converge `NavSection` components
  src/components/Dropdown.vue
  src/components/EmbeddedNavSection.vue
  src/components/HeaderSection.vue
  src/components/NavSection.vue
  src/layouts/default.vue
  src/layouts/embedded-with-nav-search.vue
  src/layouts/embedded.vue
  src/layouts/with-nav-search.vue
  src/locales/po-files/openverse.pot
  src/pages/about.vue
  src/pages/audio/_id.vue
  src/pages/extension.vue
  src/pages/feedback.vue
  src/pages/index.vue
  src/pages/meta-search.vue
  src/pages/photos/_id.vue
  src/pages/search-help.vue
  src/pages/search.vue
  src/pages/sources.vue
  test/unit/specs/components/nav-section.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#455 Update Sass breakpoints to match tailwind
  src/styles/base/layout.sass
  src/styles/components/navbar.sass
  src/styles/utilities/initial-variables.scss
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#450 Update Sentry version and turn it on only for production
  nuxt.config.js
  package-lock.json
  package.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#388 Improve `Dockerfile` and enable pipeline to automate docker image generation
  .dockerignore
  .github/workflows/build.yaml
  .github/workflows/pre-build.yaml
  Dockerfile
  docker-compose.yml
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#422 Give licenses the full name and retire `LicenseIcons`
  src/components/Filters/FilterChecklist.vue
  src/components/ImageGrid/ImageCell.vue
  src/components/License/VLicense.vue
  src/components/License/meta/VLicense.stories.mdx
  src/components/LicenseIcons.vue
  src/components/SearchGridCell.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/license-icons.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/v-license.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y
