Repository WordPress/openverse-frontend, pull requests merged in 2022-10, with the labels that each got.

#1845 Split VHeader into VHeaderDesktop and VHeaderMobile components
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeader/VHeaderMobile.vue
  src/components/VHeader/meta/VHeader.stories.mdx
  src/components/VHeader/meta/VHeaderDesktop.stories.mdx
  src/components/VHeader/meta/VHeaderMobile.stories.mdx
  src/layouts/default.vue
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#1871 Hide the 'interpunct' character from the screenreaders
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#1868 Rename meta search page and all code
  nuxt.config.ts
  src/assets/screenshots/supported.png
  src/assets/screenshots/unsupported.png
  src/components/VErrorSection/VNoResults.vue
  src/components/VExternalSearch/VExternalSearchForm.vue
  src/components/VExternalSearch/VExternalSourceList.vue
  src/components/VExternalSearch/meta/VExternalSourceList.stories.mdx
  src/components/VSearchGrid.vue
  src/composables/use-pages.ts
  src/locales/en.json
  src/pages/about.vue
  src/pages/external-sources.vue
  src/pages/meta-search.vue
  test/locales/ar.json
  test/locales/es.json
  test/locales/ru.json
  test/playwright/e2e/search-types.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xs-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#1865 Add recent searches to the search store
  feat/feature-flags.json
  package.json
  pnpm-lock.yaml
  src/components/VNotificationBanner.vue
  src/composables/use-storage.ts
  src/pages/search.vue
  src/stores/search.ts
  src/utils/env.ts
  test/unit/specs/stores/search-store.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#1841 Remove span from VLink
  src/components/VContentLink/VContentLink.vue
  src/components/VLink.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1867 Add UI for recent search results
  feat/feature-flags.json
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/meta/VSearchBar.stories.mdx
  src/components/VRecentSearches/VRecentSearches.vue
  src/components/VRecentSearches/meta/VRecentSearches.stories.mdx
  src/locales/en.json
  src/stores/search.ts
  src/utils/math.ts
  tailwind.config.js
  test/playwright/e2e/recent-searches.spec.ts
  test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
  test/unit/specs/stores/search-store.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1870 TS-ify VItemGroup and VPopover components
  src/components/VItemGroup/VItem.vue
  src/components/VItemGroup/VItemGroup.vue
  src/components/VItemGroup/meta/VItemGroup.stories.js
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.vue
  src/composables/use-dialog-content.ts
  src/composables/use-focus-on-show.ts
  src/composables/use-popover-content.ts
  src/composables/use-popper.ts
  src/models/item-group.ts
  tsconfig.json
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1887 Add loading animations to the 'See Results' button
  src/components/VHeader/VHeaderMobile/VShowResultsButton.vue
  src/components/VHeader/meta/VShowResultsButton.stories.mdx
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1888 Update outdated information in `CONTRIBUTING.md` file
  CONTRIBUTING.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#1862 Replace Husky and lint-staged with pre-commit
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .lintstagedrc
  .pre-commit-config.yaml
  Dockerfile
  bin/playwright.sh
  package.json
  src/assets/browsers/chrome.svg
  src/assets/browsers/edge.svg
  src/assets/browsers/firefox.svg
  src/assets/browsers/opera.svg
  src/assets/icons/source.svg
  src/assets/licenses/pd.svg
  src/styles/tailwind.css
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1901 Fix alignment to pass Prettier check
  src/components/VHeader/VSearchBar/VSearchBar.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1902 Skip Git hooks when updating PO file
  .github/workflows/generate_pot.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1893 Make VRecentSearches ClientOnly
  src/components/VHeader/VSearchBar/VSearchBar.vue
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1889 Hide the recent searches when navigating with the keyboard
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VInputField/VInputField.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1905 Remove ignore scripts (nuxt requires it)
  Dockerfile
  bin/install-pre-commit.sh
  package.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1892 Make `isNewHeaderEnabled` a computed so that it's updated
  src/layouts/default.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1911 Fix typo in word 'occurred'
  src/locales/en.json
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#1903 Fix VSearchTypes spacings
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VContentSwitcher/meta/VSearchTypePopover.stories.mdx
  src/components/VContentSwitcher/meta/VSearchTypes.stories.mdx
  src/components/VHeader/VHeaderMobile/VContentSettingsModal.vue
  src/components/VItemGroup/VItem.vue
  test/storybook/visual-regression/v-search-types.spec.ts
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-medium-at-rest-md-linux.png
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-medium-focused-md-linux.png
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-medium-images-hovered-md-linux.png
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-small-at-rest-xl-linux.png
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-small-focused-xl-linux.png
  test/storybook/visual-regression/v-search-types.spec.ts-snapshots/v-search-types-small-images-hovered-xl-linux.png
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1916 Fix the height of the button adding a new class
  src/components/VButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1915 Fix - get this media button
  src/pages/image/_id.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1906 Close the recent searches on Shift+Tab
  src/components/VHeader/VSearchBar/VSearchBar.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1914 Update Playwright tests utilities to work both when the `new_header` flag is enabled and when it's disabled
  src/components/VHeader/VHeaderMobile/VContentSettingsButton.vue
  src/components/VHeader/VHeaderMobile/VContentSettingsModal.vue
  src/locales/en.json
  test/README.md
  test/playwright/e2e/filters-old.spec.ts
  test/playwright/e2e/mobile-menu-old.spec.ts
  test/playwright/e2e/recent-searches.spec.ts
  test/playwright/e2e/search-navigation-old.spec.ts
  test/playwright/e2e/search-query-client-old.spec.ts
  test/playwright/e2e/search-query-server-old.spec.ts
  test/playwright/e2e/search-types-old.spec.ts
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/audio-results-old.spec.ts
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-xl-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts
  test/playwright/visual-regression/components/header-old.spec.ts
  test/playwright/visual-regression/components/header.spec.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1930 Fix VButton centering
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VButton.vue
  src/pages/image/_id.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1924 Update action-setup to v.2.2.4
  .github/actions/setup-node-env/action.yml
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1934 Prevent clearing of the search bar value when homepage is hydrated
  src/assets/oops.svg
  src/components/VFourOhFour.vue
  src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue
  src/components/VHeaderOld/VSearchBar/VSearchButtonOld.vue
  src/components/VHeaderOld/VSearchBar/VStandaloneSearchBarOld.vue
  src/pages/index.vue
  src/styles/tailwind.css
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/non-existent-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#1936 Update the language selector to work with the yellow pages
  src/components/VFourOhFour.vue
  src/components/VSelectField/VSelectField.vue
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#1928 Audit VIconButton sizes and props
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VAudioTrack/meta/VAudioTrack.stories.mdx
  src/components/VAudioTrack/meta/VPlayPause.stories.mdx
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VExternalSearch/VExternalSourceList.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeader/VHeaderInternal.vue
  src/components/VHeader/VHeaderMobile/VContentSettingsModal.vue
  src/components/VHeader/VHeaderMobile/VSearchBarButton.vue
  src/components/VHeader/VSearchBar/VClearButton.vue
  src/components/VHeader/meta/VContentSettingsButton.stories.mdx
  src/components/VHeader/meta/VSearchBarButton.stories.mdx
  src/components/VIcon/VIcon.vue
  src/components/VIconButton/VIconButton.vue
  src/components/VIconButton/meta/VIconButton.stories.mdx
  src/components/VNotificationBanner.vue
  tailwind.safelist.txt
  test/storybook/visual-regression/v-icon-button.spec.ts
  test/storybook/visual-regression/v-icon-button.spec.ts-snapshots/v-icon-button-sizes-linux.png
  test/storybook/visual-regression/v-search-bar-button.spec.ts
  test/storybook/visual-regression/v-search-bar-button.spec.ts-snapshots/back-button-focused-linux.png
  test/storybook/visual-regression/v-search-bar-button.spec.ts-snapshots/back-button-hovered-linux.png
  test/storybook/visual-regression/v-search-bar-button.spec.ts-snapshots/clear-back-buttons-resting-linux.png
  test/storybook/visual-regression/v-search-bar-button.spec.ts-snapshots/clear-button-focused-linux.png
  test/storybook/visual-regression/v-search-bar-button.spec.ts-snapshots/clear-button-hovered-linux.png
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1932 Add disabled snapshots to the `action-` buttons
  test/storybook/visual-regression/v-button.spec.ts
  test/storybook/visual-regression/v-button.spec.ts-snapshots/action-menu-bordered-disabled-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/action-menu-disabled-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/action-menu-muted-disabled-linux.png
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#1918 Add the new e2e tests that work with `new_header` flag on
  src/components/VCopyButton.vue
  src/components/VHeaderOld/VHeaderFilter.vue
  src/layouts/default.vue
  src/pages/search.vue
  src/pages/search/audio.vue
  test/playwright/e2e/filters.spec.ts
  test/playwright/e2e/header-internal.spec.ts
  test/playwright/e2e/mobile-menu.spec.ts
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/e2e/search-query-client.spec.ts
  test/playwright/e2e/search-query-server.spec.ts
  test/playwright/e2e/search-types.spec.ts
  test/playwright/utils/breakpoints.ts
  test/playwright/visual-regression/components/audio-results-old.spec.ts
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement
