Repository WordPress/openverse-frontend, pull requests merged in 2022-12, with the labels that each got.

#1957 Use cookie for banners state
  src/components/VBanner/VBanners.vue
  src/components/VBanner/VMigrationNotice.vue
  src/components/VBanner/VNotificationBanner.vue
  src/components/VBanner/VTranslationStatusBanner.vue
  src/components/VTranslationStatusBanner.vue
  src/layouts/blank.vue
  src/layouts/default.vue
  src/stores/ui.ts
  src/types/banners.ts
  src/types/cookies.ts
  src/utils/translation-banner.ts
  test/playwright/e2e/migration-banner.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
  test/unit/specs/stores/ui-store.spec.js
  test/unit/test-utils/pinia.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#1997 Move all the types to /types directory
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VItemGroup/VItem.vue
  src/components/VItemGroup/VItemGroup.vue
  src/components/VItemGroup/meta/VItemGroup.stories.js
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/components/VSearchGrid.vue
  src/components/VSourcesTable.vue
  src/components/VTabs/VTab.vue
  src/components/VTabs/VTabPanel.vue
  src/components/VTabs/VTabs.vue
  src/data/media-provider-service.ts
  src/data/media-service.ts
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/pages/search/search-page.types.ts
  src/stores/active-media.ts
  src/stores/media/index.ts
  src/stores/media/related-media.ts
  src/stores/media/services.ts
  src/stores/media/single-result.ts
  src/stores/provider.ts
  src/types/fetch-state.ts
  src/types/item-group.ts
  src/types/media-provider.ts
  src/types/media.ts
  src/types/tabs.ts
  src/utils/attribution-html.ts
  src/utils/decode-media-data.ts
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#2006 Fix Audio single result layout
  package.json
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VModal/VModalContent.vue
  src/types/media.ts
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-xs-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-xs-linux.png
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#2036 Fix popover not closing on Escape or click outside
  src/components/VModal/VInputModal.vue
  src/components/VModal/VModalContent.vue
  src/composables/use-dialog-content.ts
  src/composables/use-focus-on-show.ts
  src/composables/use-popover-content.ts
  test/playwright/e2e/homepage.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#2031 Set same site to None when `new_header` is off
  src/middleware/middleware.ts
  src/stores/ui.ts
  test/unit/specs/stores/ui-store.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#2030 fix margin bottom of pages menu
  src/components/VHeaderOld/VPageMenu/VPageList.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#2042 Split the e2e and vr tests
  .github/workflows/ci.yml
  src/components/VBanner/VBanners.vue
  src/components/VHeaderOld/VHeaderOld.vue
  src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/pages/pages-single-result.spec.ts
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#2040 Added instructions for installing Node
  README.md
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#1940 Replace deprecated `set-output` command
  .github/workflows/ghcr.yml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#2053 Ping staging deployer in Slack notification
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#2045 Move getting localized search path to the search store
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcherOld/VSearchTypeItemOld.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VFourOhFour.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
  src/components/VHeaderOld/VHeaderMenu.vue
  src/components/VHeaderOld/VHeaderOld.vue
  src/pages/index.vue
  src/pages/search-help.vue
  src/stores/search.ts
  test/unit/test-utils/pinia.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#2055 Set and use `GH_SLACK_USERNAME_MAP` as an environment variable
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#2057 Try without `toJSON` function and continue in any case
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#2058 Simplify step for setting the Slack user in GH action
  .github/actions/staging-frontend-deploy/action.yml
  .github/workflows/gh-pages.yaml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#2059 Ping deployer on production Slack notification
  .github/actions/production-frontend-deploy/action.yml
  .github/actions/staging-frontend-deploy/action.yml
  .github/workflows/ghcr.yml
  .github/workflows/rollback.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#2062 Fix secret turned input in action
  .github/actions/production-frontend-deploy/action.yml
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#2065 Authenticate with `GITHUB_TOKEN` when setting up pre-commit
  .github/workflows/bundle_size.yml
  .github/workflows/ci.yml
  .github/workflows/generate_pot.yml
  .github/workflows/gh-pages.yaml
  bin/install-pre-commit.sh
  package.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#2067 Add utilities for consistent focus rings
  .storybook/decorators/with-screenshot-area.js
  nuxt.config.ts
  src/assets/icons/check.svg
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VCheckbox/VCheckbox.vue
  src/components/VCheckbox/meta/VCheckbox.stories.mdx
  src/components/meta/Focus.stories.mdx
  src/styles/tailwind.css
  tailwind.config.js
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-ltr-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-rtl-linux.png
  test/storybook/visual-regression/focus.spec.ts
  test/storybook/visual-regression/focus.spec.ts-snapshots/focus-bold-filled-linux.png
  test/storybook/visual-regression/focus.spec.ts-snapshots/focus-colored-linux.png
  test/storybook/visual-regression/focus.spec.ts-snapshots/focus-slim-filled-linux.png
  test/storybook/visual-regression/focus.spec.ts-snapshots/focus-slim-transparent-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/default-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/disabled-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/focused-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/hover-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/off-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-and-off-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-disabled-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-focused-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface
