Repository WordPress/openverse-frontend, pull requests merged in 2022-02, with the labels that each got.

#753 Use jed1x json format to correctly handle pluralization
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/locales/scripts/get-translations.js
  src/locales/scripts/jed1x-json-to-json.js
  src/locales/scripts/json-pot-helpers.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#747 Remove Jamendo and Wikimedia Commons from audio meta sources
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/utils/get-legacy-source-url.js
  test/e2e/content-types.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#755 Enable source maps in production
  nuxt.config.js
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#701 Switch to path-based i18n routing
  nuxt.config.js
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/composables/use-match-routes.js
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/pages/index.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#682 New image details page
  src/components/CopyButton.vue
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/VPhotoDetails.vue
  src/components/LicenseElements.vue
  src/components/MediaInfo/CopyLicense.vue
  src/components/MediaInfo/MediaReuse.vue
  src/components/SketchFabViewer.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/styles/components/tabs.scss
  src/styles/vocabulary.scss
  src/utils/attribution-html.js
  test/e2e/image-detail.spec.js
  test/e2e/search.spec.js
  test/unit/specs/components/ImageDetails/image-attribution.spec.js
  test/unit/specs/components/ImageDetails/image-info.spec.js
  test/unit/specs/components/ImageDetails/v-copy-license.spec.js
  test/unit/specs/components/ImageDetails/v-photo-details.spec.js
  test/unit/specs/components/copy-button.spec.js
  test/unit/specs/components/related-images.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#773 Truncate global audio text to two lines
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#763 Check for `null` localStorage explicitly
  src/utils/local.js
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#780 Fix global audio rtl close placement
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#767 Fix logo button paddings and simplify implementation
  src/components/VHeader/VLogoButton.vue
  src/components/VLogoLoader/VLogoLoader.types.js
  src/components/VLogoLoader/VLogoLoader.vue
  src/pages/index.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#768 Make audio/image pages without ids show a 404
  src/components/VFourOhFour.vue
  src/layouts/error.vue
  src/pages/audio/index.vue
  src/pages/image/index.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#783 Fix double focus ring in item groups
  src/components/VButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#563 Staging and production deployment workflows
  .github/actions/build/action.yml
  .github/workflows/build.yml
  .github/workflows/pre-build.yaml
  .github/workflows/push_production.yaml
  .github/workflows/push_staging.yaml
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#790 Remove dead a/b testing (sixpack) code
  nuxt.config.js
  src/ab-tests/experiments/donation-language.js
  src/ab-tests/index.js
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/plugins/ab-test-init.js
  src/store/abtest.js
  src/store/user.js
  src/utils/session-id.js
  src/utils/sixpack.js
  test/unit/specs/ab-tests.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#785 Adjust styles of `VContentLink`
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VContentLink/VContentLink.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#771 Add skip to content button
  src/components/VSkipToContentContainer.vue
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/utils/key-codes.js
  test/unit/specs/pages/browse-page.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#816 Complete missing props
  src/components/VFourOhFour.vue
  src/components/VHeader/VLogoButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#796 Fix homepage RTL
  src/assets/brand.svg
  src/assets/icons/openverse-logo-text.svg
  src/assets/logo.svg
  src/components/VFourOhFour.vue
  src/components/VHeader/VLogoButton.vue
  src/components/VLogoLoader/VLogoLoader.vue
  src/layouts/blank.vue
  src/pages/index.vue
  tailwind.config.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#821 Allow local network access from other devices when in development
  package.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#795 Fix unguarded `ResizeObserver` access
  src/components/VAudioTrack/VWaveform.vue
  src/mixins/iframe-height.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#770 Unify number localization strategy across the app.
  src/composables/use-get-locale-formatted-number.js
  src/composables/use-i18n-utilities.js
  src/pages/sources.vue
  test/unit/specs/composables/use-get-locale-formatted-number.spec.js
  test/unit/specs/composables/use-i18n-utilities.spec.js
  tsconfig.json
  typings/nuxt__types/index.d.ts
Labels: 🟩 priority: low, 🕹 aspect: interface, 🧰 goal: internal improvement

#829 Add a check for blank search term before searching
  src/pages/index.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#814 Set default size of VAudioTrack with a computed property
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#720 Create the Content Report flow
  src/assets/icons/radiomark.svg
  src/components/VCheckbox/VCheckbox.vue
  src/components/VCheckbox/meta/VCheckbox.stories.js
  src/components/VContentReport/VContentReportButton.vue
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VContentReport/VDmcaNotice.vue
  src/components/VContentReport/VDoneMessage.vue
  src/components/VContentReport/VOtherIssueForm.vue
  src/components/VContentReport/VReportDescForm.vue
  src/components/VContentReport/VReportError.vue
  src/components/VContentReport/meta/VContentReportPopover.stories.mdx
  src/components/VFilters/VFilterChecklist.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.vue
  src/components/VRadio/VRadio.vue
  src/components/VRadio/meta/VRadio.stories.mdx
  src/constants/content-report.js
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  tailwind.safelist.txt
  test/unit/specs/components/ContentReport/content-report-form.spec.js
  test/unit/specs/components/v-checkbox.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#826 Add underline to the "contribute a translation" link
  src/components/NotificationBanner.vue
  src/components/VNotificationBanner.vue
  src/components/VTranslationStatusBanner.vue
  src/layouts/default.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#793 Guard `local` util against thrown errors
  src/utils/local.js
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#800 Update color 'primary' to 'pink' after redesign
  src/components/VCheckbox/VCheckbox.vue
  src/components/VRadio/VRadio.vue
  tailwind.config.js
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#798 Remove usage session cookie
  package.json
  pnpm-lock.yaml
  src/data/api-service.js
  src/data/usage-data-service.js
  src/store/user.js
  src/utils/session-id.js
  test/unit/specs/store/user.spec.js
  tsconfig.json
Labels: 🟥 priority: critical, 💻 aspect: code, 🧰 goal: internal improvement

#837 Replace `@` imports with `~` imports
  src/components/FooterSection.vue
  src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
  src/pages/search/audio.vue
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#841 Fix/silence some warnings
  nuxt.config.js
  src/data/usage-data-service.js
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#788 Tweak search bar styles in homepage
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/locales/po-files/openverse.pot
  src/pages/index.vue
  test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#833 Unstuck `searchStatus` of search bar
  src/components/VHeader/VHeader.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#844 Use the correct list of filters for All content
  src/store/search.js
  src/utils/search-query-transform.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#848 Document global ref SSR safety
  src/composables/use-active-audio.js
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-window-scroll.js
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#840 Improve e2e tests
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  test/e2e/content-types.spec.js
  test/e2e/filters.spec.js
  test/e2e/homepage.spec.js
  test/e2e/resources/mock_audio_data.json
  test/e2e/resources/mock_image_data.json
  test/e2e/search-query-client.spec.js
  test/e2e/search-query-server.spec.js
  test/e2e/search.spec.js
  test/e2e/utils.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#827 Fix homepage content switcher size
  src/components/VContentSwitcher/VContentSwitcherButton.vue
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
  src/pages/index.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#854 Add default placeholder for VSearchBar
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/pages/index.vue
  test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#849 Fix global layout issues
  src/components/VContentSwitcher/VContentSwitcherButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VLogoButton.vue
  src/constants/screens.js
  src/layouts/default.vue
  src/styles/base/generic.sass
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#861 Duplicate button classnames for increased specificity
  src/components/VButton.vue
Labels: bug, 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#863 Remove unused store modules
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/store/bug-report.js
  src/store/report-content.js
  test/unit/specs/store/bug-report.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#864 Fix text colors
  src/styles/utilities/derived-variables.scss
  src/styles/utilities/initial-variables.scss
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#870 Fix inline popover content taking up space
  src/components/VPopover/VPopoverContent.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#872 Remove unused PhotoTags component
  src/components/PhotoTags.vue
  test/unit/specs/components/photo-tags.spec.js
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#869 Use single function to fetch single media item
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/store/media.js
  test/unit/specs/store/media-store.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#865 Add tags in image single result page
  src/components/AudioDetails/VAudioDetails.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VMediaTag/VMediaTag.vue
  src/components/VMediaTag/meta/VMediaTag.stories.mdx
  test/unit/specs/components/VMediaTag/v-media-tag.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#883 Remove footer and associated styles and i18n strings
  src/components/FooterSection.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/styles/vocabulary.scss
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#886 Add TESTING_GUIDELINES.md initial draft
  CONTRIBUTING.md
  TESTING_GUIDELINES.md
Labels: 🟩 priority: low, 🌟 goal: addition, 📄 aspect: text

#900 Disable friendly errors overlay
  nuxt.config.js
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#897 Remove excessive padding from VContentItem
  src/components/VContentSwitcher/VContentItem.vue
  src/components/VContentSwitcher/VContentTypes.vue
  src/components/VItemGroup/VItem.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#908 Remove outdated labelling instructions
  CONTRIBUTING.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#905 Remove unused Google Analytics code
  nuxt.config.js
  src/analytics/events.js
  src/analytics/google-analytics.js
  src/components/VMediaInfo/VCopyLicense.vue
  src/constants/action-types.js
  src/constants/store-modules.js
  src/plugins/ga.js
  src/store/attribution.js
  src/utils/env.js
  test/unit/specs/components/ImageDetails/v-copy-license.spec.js
  test/unit/specs/store/attribution.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#818 (#692) Fix duration mismatch between audio and metadata
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#879 Make VLink component that wraps around both external and internal links
  src/components/AudioDetails/VAudioDetails.vue
  src/components/AudioDetails/VRelatedAudio.vue
  src/components/DownloadButton.vue
  src/components/ExtensionBrowsers.vue
  src/components/ImageDetails/ReuseSurvey.vue
  src/components/ImageGrid/ImageCell.vue
  src/components/VAllResultsGrid/VImageCell.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VBackToSearchResultsLink.vue
  src/components/VButton.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VDmcaNotice.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VFilters/VLicenseExplanationTooltip.vue
  src/components/VFourOhFour.vue
  src/components/VHeader/VLogoButton.vue
  src/components/VHeader/VPageMenu/VPageList.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VItemGroup/VItem.vue
  src/components/VLink.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMediaTag/meta/VMediaTag.stories.mdx
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VMigrationNotice.vue
  src/components/VTranslationStatusBanner.vue
  src/pages/about.vue
  src/pages/feedback.vue
  src/pages/image/_id.vue
  src/pages/index.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/sources.vue
  src/utils/attribution-html.js
  test/unit/setup.js
  test/unit/specs/components/ImageDetails/reuse-survey.spec.js
  test/unit/specs/components/v-button.spec.js
  test/unit/specs/components/v-link.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#904 Add migration notice and translation banner to the blank layout; fix translation banner logic
  src/composables/use-i18n-sync.js
  src/layouts/blank.vue
  test/e2e/translation-banner.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#916 Disallow all link components except `<VLink>` with eslint rule
  .eslintrc.js
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#851 Remove `mediaType` from `search.query` state
  package.json
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypeRadio.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
  src/components/VFilters/VFilterChecklist.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VSearchGrid.vue
  src/composables/use-search-type.js
  src/constants/action-types.js
  src/constants/media.js
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/index.vue
  src/pages/search.vue
  src/pages/search/audio.vue
  src/store/media.js
  src/store/search.js
  src/store/types.d.ts
  src/utils/prepare-search-query-params.js
  src/utils/search-query-transform.js
  test/e2e/content-types.spec.js
  test/e2e/search-types.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/search-store.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#917 Lint TS files in Git hooks
  .lintstagedrc
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#944 Remove dead code and fix errant type
  src/composables/types.js
  src/utils/locales.js
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#893 Rename Skeleton components
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VSkeleton/VAudioTrackSkeleton.vue
  src/components/VSkeleton/VBone.vue
  src/components/VSkeleton/VGridSkeleton.vue
  src/components/VSkeleton/meta/VGridSkeleton.stories.mdx
  src/pages/search/audio.vue
  src/plugins/ua-parse.js
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#918 Enable SSR for migration banner
  src/components/VMigrationNotice.vue
  src/layouts/default.vue
  src/middleware/middleware.js
  test/e2e/migration-banner.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#892 Rename AudioDetails
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/locales/po-files/openverse.pot
  test/unit/specs/components/related-audios.spec.js
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#884 Use v-show instead of v-if for width-based condition
  src/components/License/VLicense.vue
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/pages/search/audio.vue
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/components/v-license.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#981 Split CI into discrete jobs
  .github/actions/setup-node-env/action.yml
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/pre-build.yaml
  .lintstagedrc
  src/locales/po-files/openverse.pot
  src/locales/scripts/json-to-pot.js
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#850 Update license explanation tooltip
  src/assets/licenses/remix.svg
  src/assets/licenses/sampling-plus.svg
  src/assets/licenses/sampling.svg
  src/components/LicenseElements.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VLicenseExplanation.vue
  src/components/VFilters/VLicenseExplanationTooltip.vue
  src/components/VFilters/meta/VLicenseExplanation.stories.mdx
  src/components/VIconButton/VIconButton.vue
  src/components/VLicenseElements.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VPopover/VPopoverContent.vue
  src/constants/license.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/store/search.js
  src/utils/license.js
  test/unit/specs/components/v-popover.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#990 Fix attribution HTML glyph reference and fix historical usages as well
  src/static/static/img/.DO_NOT_MOVE_THIS_DIRECTORY_OR_ITS_CONTENTS.md
  src/static/static/img/cc-by_icon.svg
  src/static/static/img/cc-cc0_icon.svg
  src/static/static/img/cc-nc_icon.svg
  src/static/static/img/cc-nd_icon.svg
  src/static/static/img/cc-pdm_icon.svg
  src/static/static/img/cc-sa_icon.svg
  src/static/static/img/cc_icon.svg
  src/utils/attribution-html.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#867 Refactor media services
  src/composables/use-related.js
  src/data/api-service.js
  src/data/audio-service.js
  src/data/base-media-service.js
  src/data/image-service.js
  src/data/media-service.js
  src/store/media.js
  src/store/types.d.ts
  src/utils/decode-data.js
  src/utils/decode-media-data.js
  test/unit/specs/components/related-audios.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/utils/decode-image-data.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#979 Add support for native TypeScript
  .babelrc
  .eslintrc.js
  .pnpmfile.cjs
  jest.config.js
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  src/components/VAudioTrack/VWaveform.vue
  src/components/VLogoLoader/meta/VLogoLoader.stories.js
  src/constants/media.js
  src/store/types.ts
  src/utils/deep-freeze.ts
  src/utils/warn.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/v-popover.spec.js
  test/unit/test-utils/svg-transform.js
  tsconfig.json
  typings/openverse/index.d.ts
  typings/vue/index.d.ts
Labels: 🟧 priority: high, 🌟 goal: addition, 🤖 aspect: dx

#993 Fix CSS import ordering
  .eslintignore
  .prettierignore
  nuxt-template-overrides/App.js
  nuxt-template-overrides/README.md
  nuxt-template-overrides/index.js
  nuxt.config.js
  package.json
  src/components/VButton.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VItemGroup/VItem.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#988 Remove z-index from brand blocking search type switcher
  src/pages/index.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#898 Avoid translating brand names
  src/components/VContentReport/VContentReportForm.vue
  src/components/VFourOhFour.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMigrationNotice.vue
  src/components/VSearchRating.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/about.vue
  src/pages/audio/_id.vue
  src/pages/extension.vue
  src/pages/feedback.vue
  src/pages/image/_id.vue
  src/pages/index.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/pages/sources.vue
  test/unit/specs/components/search-rating.spec.js
  test/unit/specs/components/v-link.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#982 Fetch single image result in `asyncData` hook instead of `fetch`
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/audio/index.vue
  src/pages/image/_id.vue
  src/pages/image/index.vue
  test/e2e/image-detail.spec.js
  test/e2e/utils.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#995 Remove unguarded localStorage access
  src/composables/use-storage.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#998 Add optional peaks key to AudioDetail interface
  src/store/types.ts
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code
