Repository WordPress/openverse-frontend, pull requests merged in 2022-06, with the labels that each got.

#1473 TS-ify use-load-more and use TS and defineComponent in layouts and pages
  src/composables/use-load-more.js
  src/composables/use-load-more.ts
  src/composables/use-media-query.ts
  src/layouts/error.vue
  src/pages/about.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1485 Fix the self-hosted config and secret for renovate cron
  .github/renovate.json
  .github/workflows/renovate.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1483 Add tailwind black text color
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1490 Add frontend redeploy task-def action
  .github/actions/frontend-deploy/action.yml
  .github/workflows/frontend_deploy.yml
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#1500 Try fixing things that might confuse deps dashboard finding
  .github/renovate.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1496 Make random waveform peaks deterministic
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VWaveform.vue
  src/locales/po-files/openverse.pot
  test/unit/specs/components/AudioTrack/waveform.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1495 Checkout before trying deploy
  .github/workflows/frontend_deploy.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1476 Fix waveform misalignment for short audios
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VWaveform.vue
  src/locales/po-files/openverse.pot
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-xl-linux.png
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1484 prevent padding to drop to 0 on large screen on audio detail view
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/pages/audio/_id.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1517 Remove secrets and fix shell step in task definition redeploy
  .github/actions/frontend-deploy/action.yml
  .github/workflows/frontend_deploy.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1512 Limit renovate to prevent eating up our GH actions
  .github/renovate.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1524 Make fetching related images on the client non-blocking
  src/components/VImageDetails/VRelatedImages.vue
  src/stores/media/related-media.ts
  src/stores/media/single-result.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1492 Add loading indication for audio
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VIconButton/VIconButton.vue
  src/constants/audio.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1474 Redirect search pages to home when no search query is present
  src/pages/search.vue
  test/playwright/e2e/redirect-queryless-searches.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1521 Set the standalone search bar height in the SearchBar component
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/locales/po-files/openverse.pot
  src/pages/index.vue
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1472 Use TS and defineComponent in the ContentSwitcher and Header
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypeRadio.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VHeader/VPageMenu/VPageList.vue
  src/components/VHeader/VPageMenu/VPageMenuButton.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1403 Fix incorrect text styles
  Dockerfile.playwright
  bin/playwright.sh
  docker-compose.playwright.yml
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/locales/po-files/openverse.pot
  src/pages/image/_id.vue
  test/playwright/README.md
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1534 Fixed Typo in README.md
  README.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#1442 Convert `duration` query parameter to `length` to match API
  src/constants/filters.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/utils/search-query-transform.ts
  test/playwright/e2e/filters.spec.ts
  test/unit/specs/stores/search-store.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1527 Prevent shifting of audio results when more results are added
  src/stores/media/index.ts
  test/unit/specs/stores/media-store.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1536 Update conditions to not run certain jobs for PRs from forks
  .github/workflows/ci.yml
  .github/workflows/ghcr.yml
Labels: 🚦 status: awaiting triage

#1526 Remove extension from title if it's the same as filetype
  src/components/VErrorSection/VErrorImage.vue
  src/models/media.ts
  src/utils/attribution-html.ts
  src/utils/decode-media-data.ts
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-xl-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
  test/unit/specs/utils/attribution-html.spec.ts
  test/unit/specs/utils/decode-image-data.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#1529 Share audio loaded state through pinia
  package.json
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/stores/media/index.ts
  test/unit/specs/stores/media-store.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1530 Add Playwright utilities
  src/components/VTranslationStatusBanner.vue
  src/locales/po-files/openverse.pot
  test/playwright/e2e/filters.spec.ts
  test/playwright/e2e/homepage.spec.ts
  test/playwright/e2e/mobile-menu.spec.ts
  test/playwright/e2e/report-media.spec.ts
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/e2e/search-query-client.spec.ts
  test/playwright/e2e/search-query-server.spec.ts
  test/playwright/e2e/search-types.spec.ts
  test/playwright/e2e/search.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/header.spec.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts
  test/playwright/visual-regression/pages/homepage.spec.ts
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/sources.spec.ts
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1480 Use `defineComponent`, add prop types and emit types
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VErrorSection/VErrorImage.vue
  src/components/VFilters/VLicenseExplanation.vue
  src/components/VLicense/VLicense.vue
  src/components/VLicense/VLicenseElements.vue
  src/components/VLogoLoader/VLogoLoader.types.js
  src/components/VLogoLoader/VLogoLoader.vue
  src/components/VMediaTag/VMediaTag.vue
  src/components/VSkeleton/VAudioTrackSkeleton.vue
  src/components/VSkeleton/VBone.vue
  src/components/VSkeleton/VGridSkeleton.vue
  tsconfig.json
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1545 Show album title on audio details page
  src/components/VAudioDetails/VAudioDetails.vue
  src/models/media.ts
  test/unit/specs/components/VAudioDetails/v-audio-details.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1493 Add a fallback for broken provider image
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VImageGrid/VImageCell.vue
  src/locales/po-files/openverse.pot
  src/pages/image/_id.vue
  tsconfig.json
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#1535 Move PO file into special branch
  .github/workflows/ci.yml
  .github/workflows/generate_pot.yml
  .gitignore
  .husky/pre-commit
  src/locales/po-files/openverse.pot
  src/locales/scripts/json-to-pot.js
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1548 Ignore package.json from renovate
  .github/renovate.json
Labels: 🚦 status: awaiting triage
