Repository WordPress/openverse-frontend, pull requests merged in 2022-11, with the labels that each got.

#1950 Fix `VInputFieldOld` component name
  src/components/VInputFieldOld/VInputFieldOld.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#1926 Typescriptify VModal components
  src/assets/icons/openverse-logo-text.svg
  src/components/VHeaderOld/VLogoButtonOld.vue
  src/components/VModal/VModal.vue
  src/components/VModal/VModalContent.vue
  src/components/VModal/VSidebarTarget.vue
  src/types/modal.ts
  tsconfig.json
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1962 add render context prop to sentry error event
  nuxt.config.ts
  src/plugins/sentry.ts
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1938 Fix filters spacing with a new header
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeader/VHeaderMobile/VContentSettingsModal.vue
  src/components/VHeaderOld/VHeaderFilter.vue
  test/playwright/visual-regression/components/filters-sidebar.spec.ts
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-ltr-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-rtl-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-ltr-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-rtl-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1964 Add docker scripts and just shim
  README.md
  justfile
  package.json
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1955 Add layout properties to the UI store and cookie to store them
  .pre-commit-config.yaml
  src/composables/use-browser-detection.ts
  src/composables/use-layout.ts
  src/composables/use-media-query.ts
  src/middleware/middleware.ts
  src/pages/preferences.vue
  src/plugins/ua-parse.ts
  src/stores/ui.ts
  src/types/cookies.ts
  test/unit/specs/components/related-audios.spec.js
  test/unit/specs/stores/ui-store.spec.js
  test/unit/test-utils/pinia.js
  typings/nuxt__types/index.d.ts
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1949 Use JSON5 for `en.json`
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
  src/locales/README.md
  src/locales/en.json
  src/locales/scripts/create-wp-locale-list.js
  src/locales/scripts/en.json5
  src/locales/scripts/get-translations.js
  src/locales/scripts/json-pot-helpers.js
  src/locales/scripts/json-to-pot.js
  src/locales/scripts/read-i18n.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1969 Add VFooter Storybook VR tests
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/navigation.ts
  test/storybook/visual-regression/v-footer.spec.ts
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-2xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-lg-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-md-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-sm-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-ltr-xs-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-2xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-lg-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-md-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-sm-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-content-rtl-xs-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-2xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-lg-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-md-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-sm-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-ltr-xs-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-2xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-lg-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-md-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-sm-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-xl-linux.png
  test/storybook/visual-regression/v-footer.spec.ts-snapshots/footer-internal-rtl-xs-linux.png
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#1961 Refactor VSearchButton
  src/components/VFourOhFour.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue
  src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue
  src/components/VHeaderOld/VSearchBar/VSearchButtonOld.vue
  src/pages/index.vue
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1973 Classes moved to static class and redundant variant prop removed #1970 #1972
  src/components/VSelectField/VSelectField.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1942 Add meta tags to pages with `new_header` enabled
  nuxt.config.ts
  src/pages/about.vue
  src/pages/external-sources.vue
  src/pages/feedback.vue
  src/pages/index.vue
  src/pages/search-help.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/pages/sources.vue
  tsconfig.json
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#1959 Improve filter sidebar rendering performance
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeaderOld/VHeaderFilter.vue
  src/layouts/default.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1978 Remove redundant language-prop 'variant' from VFourOhFour.vue
  src/components/VFourOhFour.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1996 Updated the URL for Get involved link in the navbar
  src/composables/use-pages.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1981 Add updated audio-results-old snapshots
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-desktop-xl-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results-old.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1982 Add updated non-existent page snapshots
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1984 Make z-index usage in JavaScript consistent with Tailwind
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.vue
  src/composables/use-popper.ts
  src/constants/z-indices.js
  tailwind.config.js
  tailwind.safelist.txt
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1985 Refactor `SCREEN_SIZES` to match `z-indices.js`
  src/components/VFooter/VFooter.vue
  src/composables/use-media-query.ts
  src/constants/screens.js
  tailwind.config.js
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/navigation.ts
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1983 Fix filters sidebar regression after merge
  src/layouts/default.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1992 Make the visual regression tests stricter
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VHeaderOld/VLogoButtonOld.vue
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/pages/homepage.spec.ts
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-ltr-from-search-results-xs-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/audio-rtl-from-search-results-xs-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-ltr-from-search-results-xs-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-2xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-lg-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-md-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-sm-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-xl-linux.png
  test/playwright/visual-regression/pages/pages-single-result.spec.ts-snapshots/image-rtl-from-search-results-xs-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#2000 Update about page to include external sources information
  src/locales/scripts/en.json5
  src/pages/about.vue
  test/locales/ar.json
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/about-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts-snapshots/external-sources-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/external-sources-rtl-xs-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#2002 Redirect external sources
  nuxt.config.ts
  src/composables/use-pages.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#2019 Prevent obstruction of audio player controls
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VSnackbar.vue
  src/constants/z-indices.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#2005 Fix mobile menu not closing
  src/components/VContentSwitcherOld/VMobileMenuModal.vue
  src/components/VContentSwitcherOld/VSearchTypePopoverOld.vue
  src/components/VHeaderOld/VHeaderMenu.vue
  test/playwright/e2e/mobile-menu-old.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface
