Repository WordPress/openverse-frontend, pull requests merged in 2022-07, with the labels that each got.

#1550 Fix PO generation workflow
  .github/workflows/generate_pot.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1547 Add audio duration filter clarifications as strings
  src/locales/en.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1546 Prevent hiding and reappearing of 'Load more' button and meta search
  src/components/VLoadMore.vue
  src/components/VSearchGrid.vue
  src/locales/en.json
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1554 Use image id for key to prevent weird reordering when toggling filters
  src/components/VImageGrid/VImageGrid.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1556 Deploy production frontend on release & correctly time staging deployment
  .github/actions/production-frontend-deploy/action.yml
  .github/workflows/ci.yml
  .github/workflows/ghcr.yml
  .github/workflows/push_production.yaml
  .github/workflows/push_staging.yaml
  .github/workflows/rollback.yml
  .github/workflows/staging_frontend_deploy.yml
  Dockerfile
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#1563 Fix rollback tag check
  .github/workflows/rollback.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1568 Fix flaky audio a11y tests
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/constants/audio.ts
  test/playwright/e2e/all-results-keyboard.spec.ts
  test/playwright/utils/audio.ts
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1564 Fix deploy action path
  .github/workflows/rollback.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1572 Add user agent and trailing slash
  .github/actions/setup-node-env/action.yml
  .github/workflows/ci.yml
  src/locales/scripts/axios.js
  src/locales/scripts/create-wp-locale-list.js
  src/locales/scripts/get-translations-status.js
  src/locales/scripts/get-translations.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1559 Parallelize snapshot tests
  .github/workflows/ci.yml
  bin/playwright.sh
  docker-compose.playwright.yml
  package.json
  src/utils/env.ts
  src/utils/sentry-config.ts
  test/playwright/e2e/filters.spec.ts
  test/playwright/e2e/report-media.spec.ts
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/components/audio-results.spec.ts
  test/playwright/visual-regression/components/header.spec.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts
  test/playwright/visual-regression/pages/homepage.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/sources.spec.ts
  test/unit/specs/stores/provider.spec.js
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement
