Repository WordPress/openverse-frontend, pull requests merged in 2022-03, with the labels that each got.

#1006 Image cell focus state improvements
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VImageGrid/VImageGrid.vue
  src/locales/po-files/openverse.pot
  src/pages/search/image.vue
  test/e2e/search.spec.js
  test/unit/specs/components/image-grid.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#738 Truncate text in content switcher button, allow width to change
  src/components/VContentSwitcher/VSearchTypeButton.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1023 Convert 6 utils to TypeScript
  .eslintrc.js
  Dockerfile
  nuxt-template-overrides/README.md
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  src/components/SketchFabViewer.vue
  src/components/VButton.vue
  src/components/VIcon/VIcon.vue
  src/components/VItemGroup/VItem.vue
  src/components/VModal/VMobileModalContent.vue
  src/components/VModal/VModalContent.vue
  src/components/VPopover/VPopoverContent.vue
  src/components/VPopover/meta/VPopover.stories.js
  src/components/VTeleport/VTeleportTarget.vue
  src/components/meta/DropdownButton.stories.js
  src/composables/use-focus-on-show.js
  src/data/api-service.js
  src/locales/scripts/get-validated-locales.js
  src/locales/scripts/types.d.ts
  src/store/index.js
  src/store/provider.js
  src/store/types.ts
  src/store/usage-data.js
  src/utils/console.ts
  src/utils/decode-data.js
  src/utils/decode-data.ts
  src/utils/decode-media-data.js
  src/utils/dev.js
  src/utils/env.ts
  src/utils/local.js
  src/utils/node-env.ts
  src/utils/resampling.ts
  src/utils/send-message.js
  src/utils/sentry-config.js
  src/utils/sentry-config.ts
  src/utils/string-to-boolean.js
  src/utils/string-to-boolean.ts
  src/utils/warn.js
  test/unit/specs/components/v-button.spec.js
  test/unit/specs/components/v-logo-loader.spec.js
  test/unit/specs/components/v-popover.spec.js
  test/unit/specs/utils/decode-data.spec.js
  test/unit/specs/utils/string-to-boolean.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#1011 Use props instead of store for searchTerm (query.q)
  src/components/VFilters/VFilterChecklist.vue
  src/locales/po-files/openverse.pot
  src/locales/scripts/json-to-pot.js
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  test/e2e/filters.spec.js
  test/e2e/search-types.spec.js
  test/e2e/search.spec.js
  test/unit/specs/components/ContentReport/content-report-form.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1013 Add missing labels to VPopover
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VFilters/VFilterChecklist.vue
  src/locales/po-files/openverse.pot
Labels: 🟨 priority: medium, 🛠 goal: fix, ♿️ aspect: a11y

#906 Create a proof-of-concept for Pinia migration
  .eslintrc.js
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VNoticeBar/meta/NoticeBar.stories.mdx
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/layouts/blank.vue
  src/layouts/default.vue
  src/locales/po-files/openverse.pot
  src/middleware/middleware.js
  src/mixins/iframe-height.js
  src/pages/search.vue
  src/plugins/migration-notice.js
  src/plugins/url-change.js
  src/store/active.js
  src/store/nav.js
  src/store/types.ts
  src/stores/active-media.js
  src/stores/nav.js
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/stores/active-media-store.spec.js
  test/unit/specs/stores/nav-store.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#1044 Minor improvements to `.eslintrc.js` and `package.json`
  .eslintrc.js
  package.json
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#1036 changed the scroll to top button color B->P
  src/components/VScrollButton.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1041 Add the missing tape that causes e2e errors
  test/tapes/response-49.json5
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#603 Create the updated 'No results' and 'Server timeout' sections
  src/assets/error_images/depressed_musician.jpg
  src/assets/error_images/image_info.json
  src/assets/error_images/waiting_for_a_bite.jpg
  src/components/VErrorSection/VErrorImage.vue
  src/components/VErrorSection/VErrorSection.vue
  src/components/VErrorSection/VNoResults.vue
  src/components/VErrorSection/VServerTimeout.vue
  src/components/VErrorSection/meta/VErrorSection.stories.mdx
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VSearchGrid.vue
  src/constants/errors.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/utils/attribution-html.js
  tailwind.config.js
  test/e2e/search.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1049 Add group class to audio track
  src/components/VAudioTrack/VAudioTrack.vue
Labels: 🟩 priority: low, 🛠 goal: fix, ♿️ aspect: a11y

#1035 Add width and height properties to images
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VImageGrid/VImageCell.vue
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#1052 Convert more utils to TypeScript
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/locales/po-files/openverse.pot
  src/utils/format-strings.js
  src/utils/local.ts
  src/utils/math.js
  src/utils/math.ts
  src/utils/prng.ts
  src/utils/send-message.js
  src/utils/send-message.ts
  src/utils/srand.js
  tsconfig.json
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1038 Extract filter definition to constants directory
  src/components/VFilters/VLicenseExplanation.vue
  src/constants/filters.ts
  src/store/search.js
  src/store/types.ts
  src/utils/search-query-transform.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/store/search-store.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#1046 handling null and undefined value for userAgent
  src/composables/use-browser-detection.js
  src/plugins/ua-parse.js
  typings/nuxt__types/index.d.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1063 Removed iframe-height.js and its implementations
  src/layouts/blank.vue
  src/layouts/default.vue
  src/locales/po-files/openverse.pot
  src/middleware/middleware.js
  src/mixins/iframe-height.js
  src/pages/audio/_id.vue
  test/iframe-test.html
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1070 Fix prop name mismatch
  src/components/VSearchGrid.vue
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1045 Use a non-versioned API URL to mock analytics requests, too
  package.json
  src/data/api-service.js
  src/data/bug-report-service.js
  src/data/media-provider-service.js
  src/data/media-service.js
  src/data/report-service.js
  src/data/usage-data-service.js
  src/utils/env.ts
  test/e2e/filters.spec.js
  test/proxy.js
  test/tapes/response-1.json5
  test/tapes/response-10.json5
  test/tapes/response-11.json5
  test/tapes/response-12.json5
  test/tapes/response-13.json5
  test/tapes/response-14.json5
  test/tapes/response-15.json5
  test/tapes/response-16.json5
  test/tapes/response-17.json5
  test/tapes/response-18.json5
  test/tapes/response-19.json5
  test/tapes/response-2.json5
  test/tapes/response-20.json5
  test/tapes/response-21.json5
  test/tapes/response-22.json5
  test/tapes/response-23.json5
  test/tapes/response-24.json5
  test/tapes/response-25.json5
  test/tapes/response-26.json5
  test/tapes/response-27.json5
  test/tapes/response-28.json5
  test/tapes/response-29.json5
  test/tapes/response-3.json5
  test/tapes/response-30.json5
  test/tapes/response-31.json5
  test/tapes/response-32.json5
  test/tapes/response-33.json5
  test/tapes/response-34.json5
  test/tapes/response-35.json5
  test/tapes/response-36.json5
  test/tapes/response-37.json5
  test/tapes/response-38.json5
  test/tapes/response-39.json5
  test/tapes/response-4.json5
  test/tapes/response-40.json5
  test/tapes/response-41.json5
  test/tapes/response-42.json5
  test/tapes/response-43.json5
  test/tapes/response-44.json5
  test/tapes/response-45.json5
  test/tapes/response-46.json5
  test/tapes/response-47.json5
  test/tapes/response-48.json5
  test/tapes/response-49.json5
  test/tapes/response-5.json5
  test/tapes/response-6.json5
  test/tapes/response-7.json5
  test/tapes/response-8.json5
  test/tapes/response-9.json5
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#1080 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/label_new_pr.yml
  .github/workflows/pr_label_check.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1082 Update a11y plugin and remove outdated package
  package.json
  pnpm-lock.yaml
  src/components/VContentReport/VContentReportButton.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VModal/VModal.vue
  src/components/VPopover/VPopover.vue
  src/locales/po-files/openverse.pot
  src/pages/extension.vue
Labels: 🚦 status: awaiting triage

#1084 Remove analytics code
  src/components/ImageDetails/ReuseSurvey.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/constants/store-modules.js
  src/data/usage-data-service.js
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/store/media.js
  src/store/usage-data.js
  src/store/user.js
  test/unit/specs/components/ImageDetails/reuse-survey.spec.js
  test/unit/specs/components/ImageDetails/v-copy-license.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/usage-data-store.spec.js
  test/unit/specs/store/user.spec.js
  tsconfig.json
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1097 Remove Vocabulary icon font
  src/assets/fonts/VocabularyIcons.json
  src/assets/fonts/VocabularyIcons.ttf
  src/assets/fonts/VocabularyIcons.woff
  src/components/Dropdown.vue
  src/components/VFilters/VFilterTag.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/locales/po-files/openverse.pot
  src/pages/sources.vue
  src/styles/utilities/icon-font.scss
  src/styles/vocabulary.scss
  test/unit/specs/components/__snapshots__/filter-tag.spec.js.snap
  test/unit/specs/components/dropdown.spec.js
  test/unit/specs/components/filter-tag.spec.js
Labels: 🚦 status: awaiting triage

#1095 Move typography defaults into `tailwind.css` file
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VHeader/VPageMenu/VPageList.vue
  src/styles/base/generic.sass
  src/styles/tailwind.css
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1092 Switch to css grid instead of legacy column classes in media reuse
  src/components/VMediaInfo/VMediaReuse.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1039 Extract filter store from the search store and convert it to Pinia
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VLicenseElements.vue
  src/constants/mutation-types.js
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/store/provider.js
  src/store/search.js
  src/store/types.ts
  src/stores/filter.js
  test/e2e/filters.spec.js
  test/e2e/image-detail.spec.js
  test/e2e/search-query-server.spec.js
  test/e2e/search-types.spec.js
  test/e2e/utils.js
  test/tapes/response-50.json5
  test/unit/specs/components/VHeader/v-filter-button.spec.js
  test/unit/specs/components/v-filter-checklist.spec.js
  test/unit/specs/components/v-search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/specs/store/filter-store.spec.js
  test/unit/specs/store/provider.spec.js
  test/unit/specs/store/search-store.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#1099 Add component imports, remove extra blank lines between imports
  src/components/CopyButton.vue
  src/components/ExtensionBrowsers.vue
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VBackToSearchResultsLink.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VErrorSection/VErrorSection.vue
  src/components/VFourOhFour.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/layouts/blank.vue
  src/layouts/default.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1109 Remove unused deps
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1068 Add Centre for Ageing to image meta search
  src/utils/get-legacy-source-url.js
  test/e2e/search-types.spec.js
Labels: 🟩 priority: low, 🌟 goal: addition, 🕹 aspect: interface

#1069 removing all the ' focus: ' classes from VIconButton.vue
  src/components/VIconButton/VIconButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1100 Handle waveform with `peaks` prop as a blank array
  src/components/VAudioTrack/VWaveform.vue
  src/locales/po-files/openverse.pot
  test/unit/specs/components/AudioTrack/waveform.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1115 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/label_new_pr.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1120 Update tailwindcss-rtl, talkback and typescript
  package.json
  pnpm-lock.yaml
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1098 Fix mature content report submission
  package.json
  pnpm-lock.yaml
  src/components/VContentReport/VContentReportForm.vue
  src/data/report-service.js
  src/pages/image/_id.vue
  test/unit/specs/components/v-content-report-form.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1058 Convert more utils to TypeScript
  package.json
  pnpm-lock.yaml
  src/components/DropdownButton.vue
  src/components/SketchFabViewer.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VItemGroup/VItemGroup.vue
  src/components/VPopover/VPopoverContent.vue
  src/constants/filters.ts
  src/constants/key-codes.ts
  src/constants/media.js
  src/constants/media.ts
  src/data/media-service.js
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/store/search.js
  src/store/types.ts
  src/stores/active-media.ts
  src/stores/filter.js
  src/stores/nav.ts
  src/utils/attribution-html.ts
  src/utils/decode-media-data.js
  src/utils/decode-media-data.ts
  src/utils/load-script.ts
  src/utils/search-query-transform.js
  src/utils/url-params.ts
  tailwind.safelist.txt
  test/unit/specs/utils/decode-image-data.spec.js
  test/unit/specs/utils/get-parameter-by-name.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#1112 Tweaks to the Image Details page
  src/components/VContentReport/VContentReportForm.vue
  src/components/VLicenseElements.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1137 Remove lodash.findindex from dependencies
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement, dependencies

#1072 Refactor media store results getters
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VHeader/VHeaderMenu.vue
  src/composables/use-load-more.js
  src/constants/mutation-types.js
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/search-page.types.js
  src/store/media.js
  test/unit/specs/store/media-store.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1129 Fix audio track null duration and add defaultRef
  .eslintrc.js
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/composables/default-ref.ts
  test/unit/specs/composables/default-ref.spec.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1147 Strictly filter sentry errors
  src/utils/sentry-config.ts
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1148 Hotfix for negative values in peaks
  src/components/VAudioTrack/VWaveform.vue
  src/locales/po-files/openverse.pot
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1139 Add import extension linting rule
  .eslintignore
  .eslintrc.js
  .storybook/.eslintrc.js
  .storybook/main.js
  .storybook/middleware.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
  src/components/License/VLicense.vue
  src/components/VErrorSection/VErrorImage.vue
  src/components/VFourOhFour.vue
  src/components/VHeader/VSidebarContent.vue
  src/components/VLogoLoader/meta/VLogoLoader.stories.js
  src/components/VModal/VModalTarget.vue
  src/components/VPopover/meta/VPopover.stories.js
  src/components/meta/DownloadButton.stories.js
  src/components/meta/DropdownButton.stories.js
  src/components/meta/VButton.stories.js
  src/locales/scripts/create-wp-locale-list.js
  src/pages/extension.vue
  src/pages/search.vue
  test/unit/specs/components/VMediaTag/v-media-tag.spec.js
  test/unit/specs/components/copy-button.spec.js
  test/unit/specs/components/download-button.spec.js
  test/unit/specs/components/dropdown-button.spec.js
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/loading-icon.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/components/scroll-button.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/v-checkbox.spec.js
  test/unit/specs/components/v-filter-checklist.spec.js
  test/unit/specs/components/v-license.spec.js
  test/unit/specs/components/v-search-results-title.spec.js
  test/unit/specs/locales/json-to-pot.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1134 Convert license utils and constants to TS
  src/components/License/VLicense.vue
  src/components/License/meta/VLicense.stories.mdx
  src/components/VFilters/VLicenseExplanation.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/constants/filters.ts
  src/constants/license.js
  src/constants/license.ts
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/utils/filters.js
  src/utils/license.js
  src/utils/license.ts
  test/unit/specs/store/filter-store.spec.js
  test/unit/specs/utils/license.spec.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#1131 Use links instead of buttons for header search type switcher
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/locales/po-files/openverse.pot
  test/e2e/filters.spec.js
  test/e2e/search-types.spec.js
  test/e2e/utils.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1163 Add support for TypeScript in Vue SFCs.
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  src/components/VLink.vue
  tsconfig.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement, ⌨️ tech: typescript

#1166 Remove source links from sources page
  src/pages/sources.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1144 Enable HTTPS in local development
  .gitignore
  README.md
  TESTING_GUIDELINES.md
  nuxt.config.ts
  package.json
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1150 Typescriptify `api-service`
  src/data/api-service.js
  src/data/api-service.ts
  src/store/media.js
  tsconfig.json
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1168 Update audio categories
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/constants/filters.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/playwright/e2e/filters.spec.ts
  test/unit/specs/stores/search-store.spec.js
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟥 priority: critical, ✨ goal: improvement, 📄 aspect: text

#1172 Content page component design fixes
  package.json
  pnpm-lock.yaml
  src/components/VButton.vue
  src/components/VContentPage.vue
  src/locales/po-files/openverse.pot
  src/pages/about.vue
  src/pages/feedback.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/sources.vue
  src/styles/text-only-page.scss
  tailwind.config.js
  tsconfig.json
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1183 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1182 Fix missing nuxt types
  .eslintrc.js
  nuxt.config.ts
  src/components/VLink.vue
  src/composables/use-i18n-sync.ts
  src/composables/use-i18n.ts
  src/utils/license.ts
  tsconfig.json
  typings/nuxt__types/index.d.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, ⌨️ tech: typescript

#1142 fix focus outline placement button
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VIconButton/VIconButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1187 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1186 Mock services using jest.mock
  src/stores/media.ts
  src/stores/media/index.ts
  src/stores/media/services.ts
  test/unit/specs/stores/media-store.spec.js
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1201 CopyButton style and name change; remove unused locale strings
  .eslintrc.js
  src/components/VCopyButton.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/unit/specs/components/v-copy-button.spec.js
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#1200 Remove scss lang directives from Vue SFC style tags; add eslint rule
  .eslintrc.js
  src/components/DropdownButton.vue
  src/components/ExtensionBrowsers.vue
  src/components/LoadingIcon.vue
  src/components/LocaleSelector.vue
  src/components/SketchFabViewer.vue
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VCopyButton.vue
  src/components/VErrorSection/VErrorImage.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VNotificationBanner.vue
  src/components/VSkeleton/VGridSkeleton.vue
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/extension.vue
  src/pages/sources.vue
  test/unit/specs/components/v-copy-button.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1202 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/discussion.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1204 Resolve conflicts between 3D models PRs
  src/components/VContentSwitcher/VSearchTypes.vue
  src/constants/media.ts
  src/locales/po-files/openverse.pot
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1188 updates eslint ts-node and sass-loader
  package.json
  pnpm-lock.yaml
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/layouts/blank.vue
  src/locales/po-files/openverse.pot
  test/playwright/utils/navigation.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code
