Repository WordPress/openverse-frontend, pull requests merged in 2022-01, with the labels that each got.

#555 Add stop-gap solution for e2es
  .github/workflows/ci.yml
  src/components/VMetaSearch/VMetaSearchForm.vue
  test/e2e/content-types.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🤖 aspect: dx

#566 🔄 Synced file(s) with WordPress/openverse
  .github/release-drafter.yml
  .github/release_drafter.yml
  .github/workflows/draft_release.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#557 Update API urls to avoid redirects
  src/data/api-service.js
  src/data/image-service.js
  src/data/report-service.js
  src/locales/scripts/wp-locales.json
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  test/e2e/content-types.spec.js
  test/e2e/filters.spec.js
  test/e2e/search.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#491 Add searchbar to header
  src/assets/icons/openverse-logo-text.svg
  src/components/HeaderSection.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VHeader/meta/VSearchBar.stories.mdx
  src/components/VInputField/VInputField.vue
  src/components/VInputField/meta/VInputField.stories.mdx
  src/components/VLogoLoader/VLogoLoader.vue
  src/composables/use-match-routes.js
  src/composables/use-media-query.js
  src/composables/use-search-route.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  tailwind.config.js
  test/unit/specs/components/InputField/input-field.spec.js
  test/unit/specs/components/header-section.spec.js
  test/unit/specs/components/search-grid-form.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#577 Search results title
  src/components/VSearchGrid.vue
  src/components/VSearchResultsTitle.vue
  src/locales/scripts/wp-locales.json
  test/unit/specs/components/v-search-results-title.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#562 Refactor Content report
  package.json
  pnpm-lock.yaml
  src/assets/icons/chevron-left.svg
  src/assets/icons/close.svg
  src/assets/icons/flag.svg
  src/components/ContentReport/ContentReportForm.vue
  src/components/ContentReport/DmcaNotice.vue
  src/components/ContentReport/OtherIssueForm.vue
  src/components/ContentReport/ReportError.vue
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/VPhotoDetails.vue
  src/components/MediaInfo/CopyLicense.vue
  src/components/MediaInfo/MediaLicense.vue
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VDmcaNotice.vue
  src/components/VContentReport/VDoneMessage.vue
  src/components/VContentReport/VOtherIssueForm.vue
  src/components/VContentReport/VReportError.vue
  src/constants/action-types.js
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/image/_id.vue
  src/store/bug-report.js
  src/store/provider.js
  src/store/report-content.js
  test/unit/specs/components/ContentReport/content-report-form.spec.js
  test/unit/specs/components/ImageDetails/photo-details.spec.js
  test/unit/specs/store/report-content-store.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#578 Updated load more button
  src/components/ImageGrid/ImageGrid.vue
  src/components/ImageGrid/LoadMoreButton.vue
  src/components/VButton.vue
  src/components/VLoadMore.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/pages/search/audio.vue
  test/unit/specs/components/image-grid.spec.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#573 Add API url changes to the e2e tests
  test/e2e/filters.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#586 Update references to `InputField` to point to `VInputField`
  src/components/VInputField/VInputField.vue
  src/components/VInputField/meta/VInputField.stories.mdx
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#585 Update names and references of `AudioDetails-` components
  src/components/AudioDetails/VAudioDetails.vue
  src/components/AudioDetails/VAudioTags.vue
  src/components/AudioDetails/VRelatedAudio.vue
  src/pages/audio/_id.vue
  test/unit/specs/components/related-audios.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#583 New 404 page
  src/assets/oops.svg
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VHeader/meta/VSearchBar.stories.mdx
  src/components/VInputField/VInputField.vue
  src/layouts/blank.vue
  src/layouts/error.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/locales/scripts/wp-locales.json
  tailwind.config.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#488 VHeader
  package.json
  pnpm-lock.yaml
  src/assets/icons/filter.svg
  src/assets/icons/openverse-logo-text.svg
  src/assets/oops.svg
  src/components/Header/SearchBar/SearchButton.vue
  src/components/HeaderSection.vue
  src/components/SearchGridForm.vue
  src/components/VButton.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VFilterDisplay.vue
  src/components/VFilters/VFilterTag.vue
  src/components/VFilters/VLicenseExplanationTooltip.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/README.md
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VHeader/VSearchBar/meta/VSearchBar.stories.mdx
  src/components/VHeader/meta/VFilterButton.stories.mdx
  src/components/VHeader/meta/VHeader.stories.mdx
  src/components/VHeader/meta/VSearchBar.stories.mdx
  src/components/VInputField/VInputField.vue
  src/components/VInputField/meta/VInputField.stories.mdx
  src/components/VLogoLoader/VLogoLoader.vue
  src/composables/use-event-listener.js
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-match-routes.js
  src/composables/use-media-query.js
  src/composables/use-window-scroll.js
  src/composables/window.js
  src/layouts/blank.vue
  src/layouts/default.vue
  src/layouts/error.vue
  src/layouts/with-nav-search.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/locales/scripts/untranslated-locales.json
  src/locales/scripts/wp-locales.json
  src/pages/search.vue
  src/styles/global.scss
  tailwind.config.js
  test/unit/specs/components/InputField/input-field.spec.js
  test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
  test/unit/specs/components/VHeader/v-filter-button.spec.js
  test/unit/specs/components/filter-checklist.spec.js
  test/unit/specs/components/filter-display.spec.js
  test/unit/specs/components/filter-tag.spec.js
  test/unit/specs/components/header-section.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/search-grid-form.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#600 Show a generated artwork when the audio thumbnail is absent
  src/components/AudioThumbnail/AudioThumbnail.vue
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/components/VAudioThumbnail/meta/VAudioThumbnail.stories.mdx
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#580 Ignore wp-locales file
  .gitignore
  package.json
  src/locales/scripts/untranslated-locales.json
  src/locales/scripts/wp-locales.json
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#599 Combine layouts into a single default
  src/layouts/default.vue
  src/layouts/with-nav-search.vue
  src/pages/about.vue
  src/pages/audio/_id.vue
  src/pages/extension.vue
  src/pages/feedback.vue
  src/pages/image/_id.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/sources.vue
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#604 Add header icons
  src/assets/icons/all-content.svg
  src/assets/icons/audio-content.svg
  src/assets/icons/caret-down.svg
  src/assets/icons/close.svg
  src/assets/icons/ellipsis.svg
  src/assets/icons/help.svg
  src/assets/icons/image-content.svg
  src/assets/icons/video-content.svg
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#605 Fix error when `<rect>` dimensions are negative
  src/components/VAudioTrack/VWaveform.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#560 Add `VContentLink` component
  playwright.config.js
  src/assets/icons/audio-wave.svg
  src/assets/icons/image.svg
  src/components/VContentLink/VContentLink.vue
  src/components/VContentLink/meta/VContentLink.stories.js
  src/components/VInputField/meta/VInputField.stories.mdx
  src/composables/use-i18n-utilities.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/e2e/content-types.spec.js
  test/e2e/search-query-client.spec.js
  test/unit/specs/components/v-content-link.spec.js
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#571 Remove sample audio data
  src/data/audio-service.js
  src/data/sample-audio-responses.json
Labels: 🟨 priority: medium, 🚧 status: blocked, ✨ goal: improvement, 💻 aspect: code

#595 Set up global audio player
  src/assets/icons/close-small.svg
  src/components/VAudioTrack/VAudioController.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/constants/mutation-types.js
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/store/active.js
  src/store/index.js
  test/unit/specs/components/AudioTrack/audio-track.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#606 Open filters in sidebar or modal from the header
  playwright.config.js
  src/components/ImageDetails/VPhotoDetails.vue
  src/components/VCheckbox.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VSidebarContent.vue
  src/components/VModal/VMobileModalContent.vue
  src/components/VModal/VSidebarTarget.vue
  src/components/VScrollButton.vue
  src/components/VTeleport/VTeleportTarget.vue
  src/composables/use-event-listener.js
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-media-query.js
  src/composables/use-scroll.js
  src/composables/use-window-scroll.js
  src/layouts/default.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/locales/scripts/untranslated-locales.json
  src/locales/scripts/wp-locales.json
  src/pages/search.vue
  src/pages/search/index.vue
  src/store/media.js
  src/styles/base/generic.sass
  src/styles/base/layout.sass
  test/e2e/content-types.spec.js
  test/e2e/filters.spec.js
  test/e2e/homepage.spec.js
  test/e2e/search-query-client.spec.js
  test/e2e/search-query-server.spec.js
  test/e2e/search.spec.js
  test/unit/specs/components/VHeader/v-filter-button.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#611 Update the layout sizes to match Figma mockups
  src/pages/search/audio.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#617 Audio fixes
  src/components/AudioDetails/VAudioDetails.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#620 Add missing strings
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#619 Show deprecated licenses
  src/components/License/VLicense.vue
  src/constants/license.js
  test/unit/specs/components/v-license.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#621 Refactor fetching for all media
  src/components/ImageGrid/ImageGrid.vue
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VHeader/VHeader.vue
  src/composables/use-load-more.js
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/store/media.js
  src/store/types.d.ts
  src/utils/prepare-search-query-params.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/v-content-link.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/search-store.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#625 Stop logging vuex stuff
  src/store/index.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#624 Remove wp-locales from git
  src/locales/scripts/wp-locales.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#607 Add Content Switcher component
  package.json
  pnpm-lock.yaml
  src/assets/icons/checkmark.svg
  src/components/VButton.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VContentSwitcher/VContentSwitcherButton.vue
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
  src/components/VContentSwitcher/VContentTypes.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VHeader/VPageMenu/VPageList.vue
  src/components/VHeader/VPageMenu/VPageMenuButton.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VItemGroup/VItem.vue
  src/components/VItemGroup/VItemGroup.vue
  src/components/VModal/VMobileModalContent.vue
  src/components/VPopover/VPopover.vue
  src/components/VTeleport/VTeleportTarget.vue
  src/composables/use-content-type.js
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-pages.js
  src/constants/media.js
  src/layouts/default.vue
  src/locales/en.json
  src/pages/search.vue
  src/store/search.js
  src/utils/search-query-transform.js
  test/e2e/search-query-client.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#627 Do not automatically include the preview URL into the list of download formats
  src/components/VAudioTrack/layouts/VFullLayout.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#597 Add small dropdown button variant
  src/components/DownloadButton.vue
  src/components/DropdownButton.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VButton.vue
  src/components/meta/DropdownButton.stories.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#622 Add VPill component
  src/components/VPill.vue
  src/components/meta/VPill.stories.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#634 Final locale removal
  src/locales/scripts/untranslated-locales.json
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#638 Add interaction styles to the content switcher
  src/components/VButton.vue
  src/components/VContentSwitcher/VContentTypes.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VItemGroup/VItem.vue
  src/styles/accent.scss
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#642 Fix docker builds
  package.json
  pnpm-lock.yaml
  src/components/VItemGroup/VItemGroup.vue
  src/composables/use-body-scroll-lock.js
  src/composables/use-event-listener-outside.js
  src/composables/use-focus-on-blur.js
  src/composables/use-focus-on-hide.js
  src/composables/use-focus-on-show.js
  src/composables/use-hide-on-click-outside.js
Labels: bug, 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#633 Fix audio waveform seeking behaviors
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VWaveform.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#648 Ignoring extra files
  .gitignore
  jest.config.js
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#647 Replace plain `<img>` tag with `VAudioThumbnail` component
  src/components/AudioDetails/VAudioDetails.vue
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/utils/math.js
  src/utils/prng.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#593 Add redesigned homepage
  nuxt.config.js
  src/assets/homepage_images/Olympics-1.jpg
  src/assets/homepage_images/Olympics-2.jpg
  src/assets/homepage_images/Olympics-3.jpg
  src/assets/homepage_images/Olympics-4.jpg
  src/assets/homepage_images/Olympics-5.jpg
  src/assets/homepage_images/Olympics-6.jpg
  src/assets/homepage_images/Olympics-7.jpg
  src/assets/homepage_images/Pottery-1.jpg
  src/assets/homepage_images/Pottery-2.jpg
  src/assets/homepage_images/Pottery-3.jpg
  src/assets/homepage_images/Pottery-4.jpg
  src/assets/homepage_images/Pottery-5.jpg
  src/assets/homepage_images/Pottery-6.jpg
  src/assets/homepage_images/Pottery-7.jpg
  src/assets/homepage_images/Universe-1.jpg
  src/assets/homepage_images/Universe-2.jpg
  src/assets/homepage_images/Universe-3.jpg
  src/assets/homepage_images/Universe-4.jpg
  src/assets/homepage_images/Universe-5.jpg
  src/assets/homepage_images/Universe-6.jpg
  src/assets/homepage_images/Universe-7.jpg
  src/assets/homepage_images/image_info.json
  src/constants/media.js
  src/layouts/error.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/index.vue
  tailwind.config.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#651 Add the privacy policy to the menu
  src/composables/use-pages.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#658 Fix pages menu min width
  src/components/VHeader/VPageMenu/VPageList.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#661 Fix another missing dependency lodash.set
  package.json
  pnpm-lock.yaml
  src/locales/scripts/ngx-json-to-json.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#654 Fix global audio syncing and seeking issues
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/composables/use-active-audio.js
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#618 All results grid
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  src/components/ImageGrid/ImageCell.vue
  src/components/ImageGrid/ImageGrid.vue
  src/components/SearchGridCell.vue
  src/components/SearchTypeTabs.vue
  src/components/SearchTypeToggle.vue
  src/components/Skeleton/GridSkeleton.vue
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAllResultsGrid/VImageCell.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VContentLink/meta/VContentLink.stories.js
  src/components/VFilters/VFilterDisplay.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeroSection.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VSearchGrid.vue
  src/composables/use-load-more.js
  src/constants/action-types.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/index.vue
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/store/media.js
  src/store/search.js
  src/store/types.d.ts
  src/utils/env.js
  src/utils/prepare-search-query-params.js
  src/utils/search-query-transform.js
  src/utils/srand.js
  tailwind.config.js
  test/unit/specs/components/__snapshots__/filter-display.spec.js.snap
  test/unit/specs/components/filter-display.spec.js
  test/unit/specs/components/hero-section.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/v-content-link.spec.js
  test/unit/specs/store/media-store.spec.js
  test/unit/specs/store/search-store.spec.js
Labels: 🟥 priority: critical, 🌟 goal: addition, 🕹 aspect: interface

#666 Use `propTypes` as `props`
  src/components/VAudioTrack/VAudioTrack.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#655 Cleanup assets
  src/assets/animaldiversity_logo.png
  src/assets/bhl_logo.png
  src/assets/brooklyn_museum_logo.png
  src/assets/capl_logo.png
  src/assets/cc_icon.svg
  src/assets/cleveland.png
  src/assets/deviantart_logo.png
  src/assets/digitaltmuseum_logo.png
  src/assets/flickr_icon.png
  src/assets/floraon_logo.png
  src/assets/geographorguk_logo.gif
  src/assets/logo-cloud.png
  src/assets/logo.svg
  src/assets/mccordmuseum_logo.png
  src/assets/met_logo.png
  src/assets/museumvictoria_logo.png
  src/assets/nhm_logo.png
  src/assets/phylopic_logo.png
  src/assets/rawpixel_logo.png
  src/assets/rijksmuseum_logo.png
  src/assets/sketchfab_logo.png
  src/assets/smk_logo.png
  src/assets/svg-silh_logo.png
  src/assets/thingiverse_logo.png
  src/assets/thorvaldsensmuseum_logo.png
  src/assets/wikimedia_logo.png
  src/assets/worms_logo.png
  src/components/NavSection.vue
  src/components/VHeroSection.vue
  test/unit/specs/components/hero-section.spec.js
  test/unit/specs/components/nav-section.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#664 Remove events from `VAudioThumbnail` stories
  src/components/VAudioThumbnail/meta/VAudioThumbnail.stories.mdx
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#669 Use 's' audio track layout for mobile
  src/pages/search/audio.vue
  test/e2e/content-types.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#660 Fix homepage accessibility
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VInputField/VInputField.vue
  src/components/VInputField/meta/VInputField.stories.mdx
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/index.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#665 Add stories for the content type switcher
  src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#677 Add a transparent border to filter button
  src/components/VButton.vue
  src/components/VHeader/VFilterButton.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#679 Increase space between audio results
  src/pages/search/audio.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#681 Notices for Jamendo tracks when seeking is impossible
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  src/components/VAudioTrack/VWaveform.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/composables/use-browser-detection.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/plugins/ua-parse.js
  test/unit/specs/components/AudioTrack/audio-track.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#678 Fix spacing issues in the Row S layout
  src/components/VAudioTrack/layouts/VRowLayout.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#683 All results audio tabbing, single result link, and play/pause fixes
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VIconButton/VIconButton.vue
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#637 Add 'beta' VPill to Audio in the content switcher
  src/components/VButton.vue
  src/components/VContentSwitcher/VContentItem.vue
  src/components/VContentSwitcher/VContentSwitcherButton.vue
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
  src/components/VContentSwitcher/VContentTypes.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VItemGroup/VItem.vue
  src/components/VItemGroup/VItemGroup.vue
  src/composables/use-content-type.js
  src/constants/media.js
  src/locales/en.json
  src/styles/accent.scss
  test/e2e/homepage.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#685 Always show search title, even when search has no results
  src/components/VItemGroup/VItem.vue
  src/components/VSearchGrid.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#684 Prevent vertical movement in filters
  src/components/VFilters/VSearchGridFilter.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#699 Add `pnpm install` to dev script
  package.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#704 Add titles to pages
  src/pages/about.vue
  src/pages/audio/_id.vue
  src/pages/extension.vue
  src/pages/feedback.vue
  src/pages/image/_id.vue
  src/pages/meta-search.vue
  src/pages/search-help.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/pages/sources.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#712 Prevent content switcher dropdown from shifting horizontally
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#693 Allow toggling playback using spacebar from the waveform
  src/components/DropdownButton.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VItemGroup/VItemGroup.vue
  src/utils/key-codes.js
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#717 Remove unused components
  package.json
  src/components/AppModal.vue
  src/components/HomeLicenseFilter.vue
  src/components/SearchGridCell.vue
  src/components/SearchGridForm.vue
  src/components/SearchTypeTabs.vue
  src/components/SearchTypeToggle.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VSaferBrowsing.vue
  src/components/meta/SearchTypeToggle.stories.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/unit/specs/components/home-license-filter.spec.js
  test/unit/specs/components/search-grid-cell.spec.js
  test/unit/specs/components/search-type-toggle.spec.js
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#695 Allow focusing specific element when opening modal
  src/components/VContentSwitcher/VContentTypes.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VModal/VMobileModalContent.vue
  src/components/VModal/VModal.vue
  src/components/VModal/VModalContent.vue
  src/components/VModal/meta/VModal.stories.js
  src/composables/use-dialog-content.js
  src/composables/use-focus-on-show.js
  test/unit/specs/components/v-modal.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, ♿️ aspect: a11y

#724 Fix focus-visible for Safari
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  src/components/VButton.vue
  src/plugins/focus-visible.js
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#719 Use `VPopover` for the content report form
  src/components/ImageDetails/VPhotoDetails.vue
  src/components/VContentReport/VContentReportForm.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.types.js
  src/components/VPopover/VPopoverContent.vue
  src/styles/global.scss
  tailwind.safelist.txt
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#707 Refactor the usage of i18n result count computation
  src/components/VContentLink/VContentLink.vue
  src/components/VHeader/VHeader.vue
  src/components/VSearchGrid.vue
  src/composables/use-i18n-utilities.js
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  test/e2e/homepage.spec.js
  test/unit/specs/composables/use-i18n-utilities.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#727 Style links globally
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VContentLink/VContentLink.vue
  src/styles/tailwind.css
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#735 Truncate row layout audio titles
  src/components/VAudioTrack/layouts/VRowLayout.vue
Labels: bug, 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#736 Expose `close` to popover content via slot props
  src/components/ImageDetails/VPhotoDetails.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/meta/VPopover.stories.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#718 Fix header items not fitting in
  src/components/VContentSwitcher/VContentSwitcherButton.vue
  src/components/VContentSwitcher/VContentSwitcherPopover.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VHeaderMenu.vue
  src/components/VHeader/VLogoButton.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VIcon/VIcon.vue
  src/components/VIconButton/VIconButton.vue
  src/components/VInputField/VInputField.vue
  src/components/VLogoLoader/VLogoLoader.vue
  src/components/VModal/VMobileModalContent.vue
  src/pages/index.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#748 Add inline-start border to filters on desktop
  src/components/VFilters/VSearchGridFilter.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#716 Add homepage content switcher for mobile screens
  src/components/VContentSwitcher/VContentTypeButton.vue
  src/pages/index.vue
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface
