Repository WordPress/openverse-frontend, pull requests merged in 2022-05, with the labels that each got.

#1330 Add defineEvent emit type helper
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VInputField/VInputField.vue
  src/components/VNotificationBanner.vue
  src/types/emits.ts
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement, ⌨️ tech: typescript

#1332 Add bundle size reporting to PRs
  .github/workflows/bundle_size.yml
  nuxt.config.ts
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#1371 Handle unknown creator in attribution
  src/models/media.ts
  src/utils/attribution-html.ts
  test/unit/specs/utils/attribution-html.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#1238 Move useLoadMore functionality in the Load More component
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VLoadMore.vue
  src/locales/po-files/openverse.pot
  src/pages/search/audio.vue
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/related-images.spec.js
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1334 Try publishing Storybook/Tailwind config previews per PR
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/pr_closed.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1321 Replace lodash.clonedeep with rfdc
  package.json
  pnpm-lock.yaml
  src/constants/filters.ts
  src/stores/search.ts
  src/types/utils.ts
  src/utils/clone.ts
  src/utils/search-query-transform.ts
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1374 Prevent renovatebot from pinning dependencies
  .github/renovate.json
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1317 Create VSourcesTable component
  package.json
  pnpm-lock.yaml
  src/components/TableSortIcon.vue
  src/components/VSourcesTable.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/sources.vue
  src/styles/components/table.sass
  src/styles/vocabulary.scss
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-2xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-lg-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-md-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-sm-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-xs-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-2xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-lg-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-md-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-sm-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-xs-linux.png
  tsconfig.json
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1272 Add breakpoint based modal variations
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VModal/VMobileModalContent.vue
  src/components/VModal/VModalContent.vue
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1270 Create a proof-of-concept for feature flags
  feat/feature-flags.json
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  src/components/VCheckbox/VCheckbox.vue
  src/constants/deploy-env.ts
  src/constants/feature-flag.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/middleware/middleware.ts
  src/pages/preferences.vue
  src/stores/feature-flag.ts
  src/types/feature-flag.ts
  test/unit/specs/stores/feature-flag-store.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#1350 Fix back to search link for pages in other languages
  src/components/VBackToSearchResultsLink.vue
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/e2e/search.spec.ts
  tsconfig.json
  typings/openverse/index.d.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1314 Publish branch and main images to ghcr
  .github/workflows/ghcr.yml
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#1349 Await fetching related media in the single result store
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VImageGrid/VImageGrid.vue
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/stores/media/single-result.ts
  test/unit/specs/stores/single-result-store.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1386 Fix mobile menu modals not opening for the second time
  src/components/VHeader/VHeaderFilter.vue
  src/components/VModal/VModalContent.vue
  src/composables/use-dialog-content.js
  test/playwright/e2e/mobile-menu.spec.ts
  test/playwright/utils/navigation.ts
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1383 Fix stories for `VContentLink` and `VSearchTypePopover`
  src/components/VContentLink/meta/VContentLink.stories.js
  src/components/VContentSwitcher/meta/VSearchTypePopover.stories.mdx
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1387 Handle attribution when title is blank
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/utils/attribution-html.ts
  test/unit/specs/utils/attribution-html.spec.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#1385 Fix pnpm + docker
  .github/workflows/ghcr.yml
  .pnpm-version
  Dockerfile
  Dockerfile.playwright
  README.md
  bin/playwright.sh
  docker-compose.playwright.yml
  docker-compose.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1337 Allow running prod ECS deployment action from ref
  .github/workflows/push_production.yaml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1376 Make "Back to Search Results" link bigger on mobile
  src/components/VBackToSearchResultsLink.vue
  src/pages/image/_id.vue
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#1389 Replace `lodash.sortby` and fix sources table ordering by url
  package.json
  pnpm-lock.yaml
  src/components/VSourcesTable.vue
  test/unit/specs/components/v-modal.spec.js
  test/unit/specs/components/v-sources-table.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1390 Remove focus on SearchBar after submit
  src/components/VHeader/VHeader.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1325 Update sketchfab viewer aspect ratio
  src/components/SketchFabViewer.vue
  src/components/VSketchFabViewer.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/image/_id.vue
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1392 Update VCheckbox component and its story
  src/assets/icons/checkmark.svg
  src/components/VCheckbox/VCheckbox.vue
  src/components/VCheckbox/meta/VCheckbox.stories.js
  src/components/VCheckbox/meta/VCheckbox.stories.mdx
  test/storybook/visual-regression/v-checkbox.spec.ts
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/default-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/off-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-linux.png
  tsconfig.json
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1381 Fix image size jumps on single result
  src/locales/po-files/openverse.pot
  src/pages/image/_id.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1404 Add pnpm pinning to ECR image push
  .github/actions/build/action.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1394 Tab order
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VScrollButton.vue
  src/components/VSearchGrid.vue
  src/composables/use-filter-sidebar-visibility.js
  src/composables/use-filter-sidebar-visibility.ts
  src/composables/use-focus-filters.ts
  src/composables/use-popover-content.js
  src/composables/use-popper.js
  src/constants/filters.ts
  src/locales/po-files/openverse.pot
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/stores/search.ts
  src/utils/focus-management.ts
  test/unit/specs/components/v-filter-checklist.spec.js
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#1291 Update a few more additional Dependencies
  .github/actions/build/action.yml
  package.json
  pnpm-lock.yaml
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1406 Try fixing build action
  .github/actions/build/action.yml
Labels: 🚦 status: awaiting triage

#1407 Update actions for forks vs main repo
  .github/workflows/bundle_size.yml
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/ghcr.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1411 Ignore workflow files in Renovate
  .github/renovate.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1414 Fix duplicated shell property in the staging build config; fix staging deploys
  .github/actions/build/action.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1402 Add debugging instructions in PRs with failing Playwright tests
  .github/workflows/ci.yml
  test/playwright/README.md
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1415 Make the popover positioning strategy configurable
  src/components/VFilters/VFilterChecklist.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.types.js
  src/composables/use-popper.js
  src/locales/po-files/openverse.pot
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1418 Use i18n from useI18n composable instead of Nuxt context
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VErrorSection/VErrorImage.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeader.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VLicense/VLicense.vue
  src/components/VLoadMore.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/components/VSketchFabViewer.vue
  src/composables/use-get-locale-formatted-number.ts
  src/composables/use-i18n-utilities.js
  src/locales/po-files/openverse.pot
  src/pages/search/audio.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#1422 Stop fetching the media twice in the search page
  .github/workflows/ci.yml
  src/pages/index.vue
  src/pages/search.vue
  src/stores/search.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1420 Remove need to pin pnpm version
  .github/actions/build/action.yml
  .github/actions/setup-node-env/action.yml
  .github/workflows/ghcr.yml
  .pnpm-version
  Dockerfile
  Dockerfile.playwright
  README.md
  bin/playwright.sh
  docker-compose.playwright.yml
  package.json
  pnpm-lock.yaml
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1438 Workflow improvements to fix CI pipline
  .github/workflows/ci.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1439 Skip previews of Storybook and Tailwind in `main` branch
  .github/workflows/ci.yml
Labels: 🚦 status: awaiting triage

#1393 Refactor license constants and utils
  src/components/VFilters/VLicenseExplanation.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/utils/attribution-html.ts
  src/utils/license.ts
  test/unit/specs/utils/attribution-html.spec.ts
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1445 Use the `route.meta` parameter to pass the path to search page
  src/composables/use-match-routes.ts
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  typings/vue-router/index.d.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1449 Tag images built for main with main
  .github/workflows/ghcr.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1452 Remove ternary from ghcr.yml
  .github/workflows/ghcr.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1450 Add OG image for audio detail page
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/utils/og.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1430 Stop opening `/search/video` from crashing the app
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VErrorSection/VNoResults.vue
  src/components/VSearchGrid.vue
  src/composables/use-search-type.js
  src/stores/media/index.ts
  src/stores/search.ts
  src/utils/search-query-transform.ts
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1458 Target slot container to copy just the text.
  src/components/VMediaInfo/VLicenseTabPanel.vue
Labels: 🚦 status: awaiting triage

#1401 Fix content shift in filter sidebar
  src/components/VFilters/VSearchGridFilter.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1451 Try fixing the tabs by using the id prop
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VTabs/VTab.vue
  src/components/VTabs/VTabPanel.vue
  src/components/VTabs/VTabs.vue
  src/models/tabs.ts
  test/unit/specs/components/v-tabs.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1453 Fix audio button rounding and global audio not closing
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VButton.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/locales/po-files/openverse.pot
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1443 Add metrics middleware
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1446 Additional sources with feature flags
  feat/feature-flags.json
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VHeader/VHeader.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/meta/VMetaSourceList.stories.mdx
  src/composables/use-match-routes.ts
  src/composables/use-search-type.ts
  src/constants/media.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/preferences.vue
  src/pages/search/model-3d.vue
  src/stores/feature-flag.ts
  src/stores/media/index.ts
  src/stores/search.ts
  src/utils/get-additional-sources.ts
  src/utils/search-query-transform.ts
  test/unit/specs/stores/feature-flag-store.spec.js
  test/unit/specs/stores/search-store.spec.js
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#1465 Add renovate cron workflow
  .github/workflows/renovate.yml
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#1466 Scroll to top after submit a new search
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/pages/sources.vue
  test/playwright/e2e/search.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1460 Load provider filters (without local file)
  src/middleware/middleware.ts
  src/pages/search.vue
  src/stores/provider.ts
  src/stores/search.ts
  test/playwright/e2e/filters.spec.ts
  test/tapes/related_audio_632d0076-fdbd-4919-8b8f-b498ef246ee8_keep-alive.json5
  test/tapes/search_audio_q=birds&source=freesound_close.json5
  test/tapes/search_images_q=birds&source=flickr_close.json5
  test/unit/specs/stores/provider.spec.js
  test/unit/specs/stores/search-store.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1470 Fix mobile homepage jumping
  src/components/VHeader/VSearchBar/VSearchBar.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VInputField/VInputField.vue
  src/pages/index.vue
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/index-ltr-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/index-ltr-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/index-rtl-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/index-rtl-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/unfocused-search-ltr-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/unfocused-search-ltr-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/unfocused-search-rtl-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/unfocused-search-rtl-xs-linux.png
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface
