Repository WordPress/openverse-frontend, pull requests merged in 2022-04, with the labels that each got.

#1215 Update @intlify/eslint-plugin-vue-i18n, vue-tsc & lint-staged
  package.json
  pnpm-lock.yaml
Labels: 🚦 status: awaiting triage

#1224 Fix VErrorSection stories
  src/components/VErrorSection/meta/VErrorSection.stories.mdx
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1218 Convert stories to composition API and fix broken ones
  src/components/VAudioThumbnail/meta/VAudioThumbnail.stories.mdx
  src/components/VAudioTrack/meta/VAudioTrack.stories.mdx
  src/components/VAudioTrack/meta/VPlayPause.stories.mdx
  src/components/VAudioTrack/meta/VWaveform.stories.mdx
  src/components/VContentReport/meta/VContentReportPopover.stories.mdx
  src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
  src/components/VErrorSection/meta/VErrorSection.stories.mdx
  src/components/VFilters/meta/VLicenseExplanation.stories.mdx
  src/components/VHeader/VSearchBar/meta/VSearchBar.stories.mdx
  src/components/VHeader/meta/VHeader.stories.mdx
  src/components/VIcon/meta/VIcon.stories.mdx
  src/components/VIconButton/meta/VIconButton.stories.mdx
  src/components/VInputField/meta/VInputField.stories.mdx
  src/components/VItemGroup/meta/VItemGroup.stories.js
  src/components/VLogoLoader/meta/VLogoLoader.stories.js
  src/components/VLogoLoader/meta/VLogoLoader.stories.mdx
  src/components/VMediaTag/meta/VMediaTag.stories.mdx
  src/components/VNoticeBar/meta/NoticeBar.stories.mdx
  src/components/VNoticeBar/meta/VNoticeBar.stories.mdx
  src/components/VSkeleton/meta/VGridSkeleton.stories.mdx
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1207 Clean up of `package.json` scripts
  .github/actions/setup-node-env/action.yml
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yaml
  .husky/pre-push
  Dockerfile
  README.md
  bin/playwright.sh
  package.json
  test/playwright/README.md
  test/playwright/e2e/filters.spec.ts
  test/playwright/playwright.config.ts
  test/proxy.js
  test/tapes/detail_images_53841492-9703-4892-96b4-10297dd84ed0_keep-alive.json5
  test/tapes/detail_images_cfa45160-a7be-4911-9b9f-4e66678ec7f7_keep-alive.json5
  test/tapes/detail_images_e9d97a98-621b-4ec2-bf70-f47a74380452_close.json5
  test/tapes/detail_images_ea7e24ee-1374-4c49-9f6f-5c4529b701d8_keep-alive.json5
  test/tapes/related_images_53841492-9703-4892-96b4-10297dd84ed0_keep-alive.json5
  test/tapes/related_images_e9d97a98-621b-4ec2-bf70-f47a74380452_close.json5
  test/tapes/related_images_e9d97a98-621b-4ec2-bf70-f47a74380452_keep-alive.json5
  test/tapes/related_images_ea7e24ee-1374-4c49-9f6f-5c4529b701d8_keep-alive.json5
  test/tapes/search_audio_q=birds_close.json5
  test/tapes/search_audio_q=birds_keep-alive.json5
  test/tapes/search_audio_q=cat&license=cc0_keep-alive.json5
  test/tapes/search_audio_q=cat&license_type=commercial_close.json5
  test/tapes/search_audio_q=cat_close.json5
  test/tapes/search_audio_q=cat_keep-alive.json5
  test/tapes/search_audio_q=galah&license_type=modification_keep-alive.json5
  test/tapes/search_audio_q=galah_close.json5
  test/tapes/search_audio_q=galah_keep-alive.json5
  test/tapes/search_images_extension=jpg_close.json5
  test/tapes/search_images_license_type=commercial&license=cc0&searchBy=creator&creator=cat_close.json5
  test/tapes/search_images_license_type=commercial&license=cc0&searchBy=creator&creator=cat_keep-alive.json5
  test/tapes/search_images_q=birds_close.json5
  test/tapes/search_images_q=birds_keep-alive.json5
  test/tapes/search_images_q=cat&aspect_ratio=tall_close.json5
  test/tapes/search_images_q=cat&categories=photograph_close.json5
  test/tapes/search_images_q=cat&license=by&extension=jpg_close.json5
  test/tapes/search_images_q=cat&license=cc0&aspect_ratio=tall_close.json5
  test/tapes/search_images_q=cat&license=cc0_keep-alive.json5
  test/tapes/search_images_q=cat_close.json5
  test/tapes/search_images_q=cat_keep-alive.json5
  test/tapes/search_images_q=dog&license=by&extension=jpg_keep-alive.json5
  test/tapes/search_images_q=dog_keep-alive.json5
  test/tapes/search_images_q=galah&license_type=modification_keep-alive.json5
  test/tapes/search_images_q=galah_close.json5
  test/tapes/search_images_q=galah_keep-alive.json5
  test/tapes/search_images_q=honey_close.json5
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1222 Update ESLint-related plugins and @pinia/testing
  package.json
  pnpm-lock.yaml
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1234 Fix command for building Storybook
  package.json
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1191 Fix buttons focus in old browsers
  package.json
  pnpm-lock.yaml
  src/components/VButton.vue
  src/components/VContentLink/VContentLink.vue
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/components/VContentSwitcher/VSearchTypeRadio.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VPageMenu/VPageMenuButton.vue
  src/components/VHeader/VSearchBar/VSearchButton.vue
  src/components/VItemGroup/VItem.vue
  src/locales/po-files/openverse.pot
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#1203 Add Sketchfab and Thingiverse as additional sources for 3D models
  src/components/VButton.vue
  src/components/VIcon/VIcon.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VMetaSearch/meta/VMetaSourceList.stories.mdx
  src/utils/get-additional-sources.ts
  src/utils/get-legacy-source-url.js
  test/unit/specs/utils/get-additional-sources.spec.ts
  test/unit/specs/utils/get-legacy-source-url.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#1240 Fix focus style of buttons in page menu
  src/components/VItemGroup/VItem.vue
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#1226 Convert a11y utils and prop-validators to TypeScript
  src/utils/a11y/get-tab-index.ts
  src/utils/a11y/is-native-tabbable.ts
  src/utils/a11y/supports-disabled-attribute.ts
  src/utils/prop-validators.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1233 Add types to basic components
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VButton.vue
  src/components/VCheckbox/meta/VCheckbox.stories.js
  src/components/VFilters/VFilterChecklist.vue
  src/components/VIcon/VIcon.vue
  src/components/VIconButton/VIconButton.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VLicense/VLicense.vue
  src/components/VLicense/meta/VLicense.stories.mdx
  src/components/VLicenseElements.vue
  src/components/VLoadMore.vue
  src/constants/license.ts
  src/pages/search/index.vue
  src/pages/search/search-page.types.js
  src/pages/search/search-page.types.ts
  src/utils/license.ts
  test/unit/specs/components/v-checkbox.spec.js
  test/unit/specs/components/v-license.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1210 More TS-ification and refactoring
  src/assets/licenses/cc.svg
  src/assets/licenses/pd.svg
  src/assets/licenses/sampling.plus.svg
  src/assets/licenses/zero.svg
  src/components/VErrorSection/VErrorImage.vue
  src/components/VFilters/VLicenseExplanation.vue
  src/components/VLicense/VLicense.vue
  src/components/VLicense/VLicenseElements.vue
  src/components/VLicense/meta/VLicenseElements.stories.mdx
  src/components/VLink.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/constants/license.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/pages/audio/_id.vue
  src/utils/attribution-html.ts
  src/utils/license.ts
  test/playwright/e2e/attribution.spec.ts
  test/unit/specs/utils/attribution-html.spec.ts
  test/unit/specs/utils/license.spec.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#1221 Clean tests from Vuex and bump Pinia dependencies
  package.json
  pnpm-lock.yaml
  test/unit/setup.js
  test/unit/specs/components/AudioTrack/audio-track.spec.js
  test/unit/specs/components/search-grid.spec.js
  test/unit/specs/components/v-checkbox.spec.js
  test/unit/specs/components/v-search-grid-filter.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/test-utils/render.js
  test/unit/test-utils/sample-store.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1241 Fix unruly URLs in source page table for small viewports
  bin/playwright.sh
  package.json
  pnpm-lock.yaml
  src/pages/sources.vue
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/page.ts
  test/playwright/visual-regression/homepage.spec.ts
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-lg-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-md-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-xl-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-ltr-xs-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-lg-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-md-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-sm-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-xl-linux.png
  test/playwright/visual-regression/homepage.spec.ts-snapshots/focused-search-rtl-xs-linux.png
  test/playwright/visual-regression/sources.spec.ts
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-2xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-lg-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-md-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-sm-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-ltr-xs-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-2xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-lg-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-md-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-sm-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-xl-linux.png
  test/playwright/visual-regression/sources.spec.ts-snapshots/sources-rtl-xs-linux.png
  test/proxy.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1246 Add storybook visual regression tests
  .github/workflows/ci.yml
  bin/playwright.sh
  docker-compose.playwright.yml
  jest.config.js
  package.json
  test/playwright/README.md
  test/storybook/README.md
  test/storybook/playwright.config.ts
  test/storybook/visual-regression/v-checkbox.spec.ts
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/default-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/off-linux.png
  test/storybook/visual-regression/v-checkbox.spec.ts-snapshots/on-linux.png
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#1227 Convert `report-service` to TypeScript
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VReportDescForm.vue
  src/components/VErrorSection/VErrorImage.vue
  src/components/VErrorSection/meta/VErrorSection.stories.mdx
  src/constants/content-report.js
  src/constants/content-report.ts
  src/constants/errors.ts
  src/data/report-service.ts
  test/tapes/detail_images_802d76cd-84cf-45bc-81ac-610331dab420_keep-alive.json5
  test/tapes/thumb_images_e9d97a98-621b-4ec2-bf70-f47a74380452_keep-alive.json5
  test/tapes/thumb_images_ea7e24ee-1374-4c49-9f6f-5c4529b701d8_keep-alive.json5
  tsconfig.json
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1208 Fix icon of dropdown button
  src/assets/icons/caret-down.svg
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VDownloadButton.vue
  src/components/VDropdownButton.vue
  src/components/meta/VDownloadButton.stories.js
  src/components/meta/VDropdownButton.stories.js
  src/locales/po-files/openverse.pot
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
  test/unit/specs/components/v-download-button.spec.js
  test/unit/specs/components/v-dropdown-button.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1252 Refine configurations for the vue-i18n eslint plugin
  .eslintrc.js
  package.json
  src/components/VFourOhFour.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/locales/po-files/openverse.pot
  src/pages/about.vue
  src/pages/index.vue
  src/pages/meta-search.vue
  src/pages/sources.vue
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1216 Related media store
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/composables/use-fetch-state.ts
  src/composables/use-related.js
  src/data/media-service.ts
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/stores/media/index.ts
  src/stores/media/related-media.ts
  test/unit/specs/components/related-audios.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/stores/media-store.spec.js
Labels: 🟧 priority: high, 🕹 aspect: interface, 🧰 goal: internal improvement

#1158 Convert `provider` store from Vuex to Pinia
  .babelrc
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VImageDetails/VImageDetails.vue
  src/constants/action-types.js
  src/constants/filters.ts
  src/constants/mutation-types.js
  src/constants/store-modules.js
  src/data/media-provider-service.js
  src/data/media-provider-service.ts
  src/data/media-service.ts
  src/middleware/middleware.ts
  src/models/media-provider.ts
  src/models/media.ts
  src/pages/sources.vue
  src/store/index.js
  src/store/provider.js
  src/store/types.ts
  src/stores/media/index.ts
  src/stores/provider.ts
  src/stores/search.ts
  src/utils/env.ts
  src/utils/pinia-state.ts
  src/utils/search-query-transform.ts
  test/storybook/playwright.config.ts
  test/tapes/related_images_802d76cd-84cf-45bc-81ac-610331dab420_keep-alive.json5
  test/tapes/thumb_images_802d76cd-84cf-45bc-81ac-610331dab420_keep-alive.json5
  test/tapes/thumb_images_e9d97a98-621b-4ec2-bf70-f47a74380452_keep-alive.json5
  test/tapes/thumb_images_ea7e24ee-1374-4c49-9f6f-5c4529b701d8_keep-alive.json5
  test/unit/specs/store/provider.spec.js
  test/unit/specs/stores/media-store.spec.js
  test/unit/specs/stores/provider.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1259 Convert search store to an options store
  src/pages/index.vue
  src/stores/search.ts
  test/unit/specs/stores/search-store.spec.js
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1260 Convert `media` store to an options store
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/locales/po-files/openverse.pot
  src/pages/audio/_id.vue
  src/pages/image/_id.vue
  src/pages/index.vue
  src/stores/media/index.ts
  src/stores/media/related-media.ts
  src/stores/media/single-result.ts
  test/unit/specs/stores/media-store.spec.js
  test/unit/specs/stores/single-result-store.spec.js
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1243 Fix audio results not being keyboard accessible in all results view
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VWarningSuppressor.vue
  src/constants/key-codes.ts
  src/locales/en.json
  src/locales/po-files/openverse.pot
  test/playwright/e2e/all-results-keyboard.spec.ts
  tsconfig.json
Labels: 🟥 priority: critical, 🛠 goal: fix, ♿️ aspect: a11y

#1249 Remove usage of legacy classes
  src/components/VMetaSearch/VMetaSearchForm.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface, 🎨 tech: css

#1273 Clean up after Pinia conversion
  nuxt.config.ts
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/meta/VFilterButton.stories.mdx
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VSearchGrid.vue
  src/data/media-service.ts
  src/store/types.ts
  src/stores/search.ts
  src/utils/get-additional-sources.ts
  src/utils/prepare-search-query-params.ts
  src/utils/search-query-transform.ts
  test/unit/specs/components/related-audios.spec.js
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1274 Convert nav store to an options store
  src/layouts/blank.vue
  src/layouts/default.vue
  src/middleware/middleware.ts
  src/plugins/migration-notice.ts
  src/plugins/url-change.ts
  src/stores/nav.ts
  src/stores/navigation.ts
  test/unit/specs/stores/nav-store.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1247 TypeScript-ify use pages
  src/composables/use-pages.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1177 Use singular `category` API param
  src/stores/search.ts
  src/utils/search-query-transform.ts
  test/playwright/e2e/search-query-client.spec.ts
  test/tapes/search_images_q=cat&categories=photograph_close.json5
  test/unit/specs/utils/search-query-transform.spec.js
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#1248 updated @nuxtjs/svg @nuxtjs/composition-api
  package.json
  pnpm-lock.yaml
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1283 Add tailwind config viewer to GH pages
  .github/workflows/gh-pages.yaml
  .gitignore
  package.json
  pnpm-lock.yaml
  src/stories/Introduction.stories.mdx
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1282 Upgrade all warnings to errors that we control
  .eslintrc.js
  .lintstagedrc
  .storybook/.eslintrc.js
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1276 Media reporting e2e tests, single audio support, style updates, and accessibility improvements
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VContentReport/VContentReportButton.vue
  src/components/VContentReport/VContentReportForm.vue
  src/data/report-service.ts
  src/locales/po-files/openverse.pot
  test/playwright/e2e/report-media.spec.ts
  test/unit/specs/components/v-content-report-form.spec.js
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1281 Fix narrow width audio results
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/pages/search/audio.vue
  test/playwright/README.md
  test/playwright/utils/breakpoints.ts
  test/playwright/visual-regression/audio-results.spec.ts
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-desktop-xl-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-sm-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1290 Replace download button with foreign landing button
  package.json
  pnpm-lock.yaml
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VDownloadButton.vue
  src/components/VDropdownButton.vue
  src/components/meta/VDownloadButton.stories.js
  src/components/meta/VDropdownButton.stories.js
  src/locales/po-files/openverse.pot
  test/unit/fixtures/audio.js
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
  test/unit/specs/components/AudioTrack/v-full-layout.spec.js
  test/unit/specs/components/v-download-button.spec.js
  test/unit/specs/components/v-dropdown-button.spec.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1255 Fix VIconButton default variant
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VButton.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/components/VFilters/VFilterChecklist.vue
  src/components/VIconButton/VIconButton.vue
  src/locales/po-files/openverse.pot
  src/types/prop-extraction.ts
  test/playwright/visual-regression/content-report-form.spec.ts
  test/playwright/visual-regression/content-report-form.spec.ts-snapshots/content-report-focused-linux.png
  test/playwright/visual-regression/content-report-form.spec.ts-snapshots/content-report-unfocused-linux.png
  test/tapes/detail_images_feb91b13-422d-46fa-8ef4-cbf1e6ddee9b_close.json5
  test/tapes/related_images_feb91b13-422d-46fa-8ef4-cbf1e6ddee9b_close.json5
  test/tapes/related_images_feb91b13-422d-46fa-8ef4-cbf1e6ddee9b_keep-alive.json5
  test/tapes/thumb_images_55b1ada4-4346-400a-a94f-d08a39349c87_keep-alive.json5
  test/tapes/thumb_images_8a95b528-57c6-41ae-8718-bfab7c8d733a_keep-alive.json5
  test/tapes/thumb_images_feb91b13-422d-46fa-8ef4-cbf1e6ddee9b_keep-alive.json5
  test/tapes/thumb_images_ff714025-19d1-4b35-bf58-198b9f837705_keep-alive.json5
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1313 Pin node version for final production image
  Dockerfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1312 Complement to app layout issues
  src/components/VScrollButton.vue
  src/layouts/default.vue
  src/pages/search.vue
Labels: 🚦 status: awaiting triage

#1288 Only show audio category if available
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  test/tapes/related_audio_2ecd5631-c48c-4a5f-89c4-83c44dbbd365_keep-alive.json5
  test/tapes/related_images_f9384235-b72e-4f1e-9b05-e1b116262a29_keep-alive.json5
  test/unit/specs/components/AudioTrack/v-box-layout.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1338 Add some a11y properties to VSearchGridFilter
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VFilterButton.vue
  src/locales/po-files/openverse.pot
  test/playwright/e2e/filters.spec.ts
  test/playwright/utils/navigation.ts
Labels: 🚦 status: awaiting triage

#1275 Remove `mob` breakpoint and simplify VFilterButton
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VFilterButton.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VLogoButton.vue
  src/components/VHeader/meta/VFilterButton.stories.mdx
  src/composables/use-active-audio.ts
  src/composables/use-browser-detection.ts
  src/composables/use-get-locale-formatted-number.ts
  src/composables/use-media-query.ts
  src/composables/use-window-scroll.js
  src/composables/window.js
  src/constants/screens.js
  src/constants/window.ts
  src/locales/po-files/openverse.pot
  src/utils/pinia-state.ts
  test/playwright/e2e/filters.spec.ts
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
  test/playwright/visual-regression/header.spec.ts-snapshots/resting-ltr-xs-linux.png
  test/playwright/visual-regression/header.spec.ts-snapshots/resting-rtl-xs-linux.png
  test/playwright/visual-regression/header.spec.ts-snapshots/searchbar-hovered-ltr-xs-linux.png
  test/playwright/visual-regression/header.spec.ts-snapshots/searchbar-hovered-rtl-xs-linux.png
  test/storybook/utils/args.ts
  test/storybook/visual-regression/v-filter-button.spec.ts
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-2-filters-md-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-2-filters-not-scrolled-xs-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-2-filters-pressed-md-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-2-filters-scrolled-xs-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-at-rest-md-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-no-filters-not-scrolled-xs-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-no-filters-scrolled-xs-linux.png
  test/storybook/visual-regression/v-filter-button.spec.ts-snapshots/filter-button-pressed-md-linux.png
  test/unit/specs/components/VHeader/v-filter-button.spec.js
  tsconfig.json
Labels: 🟨 priority: medium, 🕹 aspect: interface, 🧰 goal: internal improvement

#1346 Convert VButton story to mdx and add all variants
  src/components/VButton.vue
  src/components/meta/VButton.stories.js
  src/components/meta/VButton.stories.mdx
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1271 TS-ify use-body-scroll-lock composable
  src/composables/use-body-scroll-lock.ts
  src/composables/use-event-listener-outside.js
  src/composables/use-focus-on-blur.js
  src/composables/use-hide-on-click-outside.js
  src/utils/dom/get-document.ts
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#1335 Stop playing audio when global player is closed
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  tsconfig.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1336 Remove lodash.set
  package.json
  pnpm-lock.yaml
  src/locales/scripts/jed1x-json-to-json.js
  src/locales/scripts/ngx-json-to-json.js
  src/locales/scripts/utils.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1296 Correct search-help links
  src/locales/po-files/openverse.pot
  src/pages/search-help.vue
  tsconfig.json
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1322 Replace lodash.throttle with throttle-debounce
  package.json
  pnpm-lock.yaml
  src/composables/use-scroll.js
  src/composables/use-window-scroll.js
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1311 TS-ify Audio components
  src/components/VAudioThumbnail/VAudioThumbnail.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VGlobalLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  src/constants/audio.ts
  src/locales/po-files/openverse.pot
  src/models/media.ts
  src/stores/active-media.ts
  src/utils/math.ts
  test/tapes/related_images_cfa45160-a7be-4911-9b9f-4e66678ec7f7_keep-alive.json5
  tsconfig.json
  typings/csstype/index.d.ts
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1351 Add e2e test for localized back to search link
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/e2e/search.spec.ts
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code
