Repository WordPress/openverse-frontend, pull requests merged in 2022-09, with the labels that each got.

#1707 Capturing Issue Description in Sentry
  src/stores/media/index.ts
  test/unit/setup-after-env.js
  test/unit/specs/stores/media-store.spec.js
  test/unit/test-utils/pinia.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, 🐛 tooling: sentry

#1646 Update the Playwright version
  package.json
  pnpm-lock.yaml
  test/README.md
  test/playwright/e2e/global-audio.spec.ts
  test/playwright/playwright.config.ts
  test/tapes/detail/audio/3051f140-304d-4217-a4ea-aaa4e2aef873_keep-alive.json5
  test/tapes/detail/audio/b502f915-adce-406b-ad87-9b17250331dd_keep-alive.json5
  test/tapes/related/audio/3051f140-304d-4217-a4ea-aaa4e2aef873_keep-alive.json5
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1771 Use the local lint-staged
  .husky/pre-commit
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1665 Add External sources popover instead of the Meta search form
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/locales/en.json
  test/locales/ar.json
  test/playwright/visual-regression/components/external-sources-section.spec.ts
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-rtl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-rtl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-rtl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xs-linux.png
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#1762 Always clean up docker container on exit, add caveat to README
  README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#1763 Show all filetypes of audio in details page
  src/components/VAudioDetails/VAudioDetails.vue
  test/unit/fixtures/audio.js
  test/unit/specs/components/VAudioDetails/v-audio-details.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1593 Enable audio interactions on the audio track component
  package.json
  pnpm-lock.yaml
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VSkipToContentContainer.vue
  src/components/VSnackbar.vue
  src/components/meta/VSnackbar.stories.mdx
  src/composables/use-seekable.ts
  src/locales/en.json
  src/pages/search/audio.vue
  src/stores/ui.ts
  src/utils/time-fmt.ts
  tailwind.config.js
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-2xl-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-lg-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-md-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-desktop-xl-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-desktop-UA-xs-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-sm-linux.png
  test/playwright/visual-regression/components/audio-results.spec.ts-snapshots/audio-results-narrow-viewport-mobile-UA-xs-linux.png
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
  test/unit/specs/components/AudioTrack/waveform.spec.js
  test/unit/specs/utils/time-fmt.spec.ts
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#1775 Switch from "black" css color keyword to "#000000" hex value
  tailwind.config.js
Labels: 🚦 status: awaiting triage

#1759 Media Copy Update
  src/components/VMediaInfo/VMediaReuse.vue
  src/locales/en.json
  test/locales/ar.json
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface, 🎨 tech: css

#1783 Delete unused font files.
  src/assets/fonts/RobotoCondensed-Bold.otf
  src/assets/fonts/RobotoCondensed-Bold.woff
  src/assets/fonts/RobotoCondensed-Bold.woff2
  src/assets/fonts/RobotoCondensed-Regular.otf
  src/assets/fonts/RobotoCondensed-Regular.woff
  src/assets/fonts/RobotoCondensed-Regular.woff2
  src/assets/fonts/SourceSansPro-Bold.otf
  src/assets/fonts/SourceSansPro-Bold.woff
  src/assets/fonts/SourceSansPro-Bold.woff2
  src/assets/fonts/SourceSansPro-Regular.otf
  src/assets/fonts/SourceSansPro-Regular.woff
  src/assets/fonts/SourceSansPro-Regular.woff2
  src/assets/fonts/SourceSansPro-SemiBold.otf
  src/assets/fonts/SourceSansPro-SemiBold.woff
  src/assets/fonts/SourceSansPro-SemiBold.woff2
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1785 The link to report at the source is incorrectly linking to the direct URL
  src/components/VContentReport/VContentReportForm.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1786 Fix load more not showing when single media type has no results
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VLoadMore.vue
  src/composables/use-load-more.ts
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/stores/media/index.ts
  test/unit/specs/stores/media-store.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1790 Disable content link when result count is zero
  src/components/VContentLink/VContentLink.vue
  test/unit/specs/components/v-content-link.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1789 Add description to the home page
  src/locales/en.json
  src/pages/index.vue
  test/locales/ar.json
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/focused-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-xl-linux.png
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#1795 Add cache to speed up the Docker build step
  .github/workflows/ghcr.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1777 Convert use-focus-on-hide to TS
  src/composables/use-dialog-content.js
  src/composables/use-focus-on-hide.ts
  src/utils/reakit-utils/focus.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1801 Convert audio as a supported media type
  src/components/VContentSwitcher/VSearchTypeItem.vue
  src/constants/media.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1731 Simplify mobile modals
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VModal/VModal.vue
  src/composables/use-focus-on-show.ts
  src/composables/use-media-query.ts
  src/composables/use-supported.ts
  src/utils/try-on-mounted.ts
  src/utils/try-on-scope-dispose.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1802 Add peaks=true to all audio searches
  src/data/api-service.ts
  src/data/media-service.ts
  src/utils/search-query-transform.ts
  test/tapes/search/audio/license_type=commercial&license=cc0&searchBy=creator&creator=cat_close.json5
  test/tapes/search/audio/license_type=commercial&license=cc0&searchBy=creator&creator=cat_keep-alive.json5
  test/tapes/search/audio/q=birds&source=freesound_close.json5
  test/tapes/search/audio/q=birds_close.json5
  test/tapes/search/audio/q=birds_keep-alive.json5
  test/tapes/search/audio/q=cat&license=cc0_keep-alive.json5
  test/tapes/search/audio/q=cat&license_type=commercial_close.json5
  test/tapes/search/audio/q=cat_close.json5
  test/tapes/search/audio/q=cat_keep-alive.json5
  test/tapes/search/audio/q=dog_close.json5
  test/tapes/search/audio/q=galah&license_type=modification_keep-alive.json5
  test/tapes/search/audio/q=galah_close.json5
  test/tapes/search/audio/q=galah_keep-alive.json5
  test/tapes/search/audio/q=honey_close.json5
  test/tapes/search/audio/q=honey_keep-alive.json5
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1813 Fix width of snackbar on mobile devices
  src/components/VSnackbar.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1812 Handle focus events that are fired when the audio player is clicked
  src/pages/search/audio.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1796 Prevent server errors if the URL has invalid characters
  nuxt.config.ts
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#1776 Convert use-focus-on-blur to TS
  src/composables/use-dialog-content.js
  src/composables/use-focus-on-blur.js
  src/composables/use-focus-on-blur.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1820 Fix `use-media-query` composable
  src/components/VHeaderOld/VHeaderOld.vue
  src/composables/use-media-query.ts
  src/layouts/default.vue
  src/types/provides.ts
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1773 Add Tailwind utility classes for Figma text styles
  src/components/VContentReport/VContentReportForm.vue
  src/components/VImageDetails/VImageDetails.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/components/VMetaSearch/VMetaSourceList.vue
  src/components/VSearchResultsTitle.vue
  src/components/VTabs/VTab.vue
  src/pages/image/_id.vue
  src/styles/tailwind.css
  tailwind.config.js
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-rtl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-rtl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-ltr-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-rtl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1814 Create the `VFooter` component
  src/assets/wordpress.svg
  src/components/VAudioTrack/VWaveform.vue
  src/components/VBrand/VBrand.vue
  src/components/VBrand/meta/VBrand.stories.mdx
  src/components/VFooter/VFooter.vue
  src/components/VFooter/meta/VFooter.stories.mdx
  src/components/VFourOhFour.vue
  src/components/VLink.vue
  src/components/VMediaInfo/VMediaReuse.vue
  src/components/VMetaSearch/VMetaSearchForm.vue
  src/components/VScrollButton.vue
  src/composables/use-pages.ts
  src/composables/use-resize-observer.ts
  src/layouts/default.vue
  src/locales/en.json
  src/pages/index.vue
  tailwind.config.js
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-rtl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/unfocused-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#1818 Add VContentSettingsButton
  src/assets/icons/source.svg
  src/components/VButton.vue
  src/components/VHeader/VContentSettingsButton.vue
  src/components/VHeader/meta/VContentSettingsButton.stories.mdx
  src/components/VIconButton/VIconButton.vue
  src/locales/en.json
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#1829 Add a click handler to VLink if it uses NuxtLink
  src/components/VLink.vue
  test/unit/setup.js
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/components/v-content-link.spec.js
  test/unit/specs/components/v-link.spec.js
  test/unit/specs/components/v-modal.spec.js
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1793 Add load more button e2e tests
  test/locales/ar.json
  test/playwright/e2e/load-more.spec.ts
  test/playwright/playwright.config.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
  test/tapes/related/audio/2e38ac1e-830c-4e9c-b13d-2c9a1ad53f95_keep-alive.json5
  test/tapes/related/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365_keep-alive.json5
  test/tapes/related/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8_keep-alive.json5
  test/tapes/related/audio/7e063ee6-343f-48e4-a4a5-f436393730f6_close.json5
  test/tapes/search/audio/q=cat&page=2&peaks=true_keep-alive.json5
  test/tapes/search/audio/q=ecommerce&peaks=true_close.json5
  test/tapes/search/audio/q=ecommerce&peaks=true_keep-alive.json5
  test/tapes/search/audio/q=horses_close.json5
  test/tapes/search/audio/q=horses_keep-alive.json5
  test/tapes/search/images/q=cat&page=2_keep-alive.json5
  test/tapes/search/images/q=ecommerce_close.json5
  test/tapes/search/images/q=ecommerce_keep-alive.json5
  test/tapes/search/images/q=horses_close.json5
  test/tapes/search/images/q=horses_keep-alive.json5
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1839 Rename the old components with the same name
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VContentSwitcherOld/VMobileMenuModal.vue
  src/components/VContentSwitcherOld/VSearchTypeButtonOld.vue
  src/components/VContentSwitcherOld/VSearchTypeItemOld.vue
  src/components/VContentSwitcherOld/VSearchTypePopoverOld.vue
  src/components/VContentSwitcherOld/VSearchTypeRadio.vue
  src/components/VContentSwitcherOld/VSearchTypesOld.vue
  src/components/VContentSwitcherOld/meta/VSearchTypePopoverOld.stories.mdx
  src/components/VFourOhFour.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VHeader/VPageMenu/VMobilePageMenu.vue
  src/components/VHeader/VPageMenu/VPageList.vue
  src/components/VHeader/VPageMenu/VPageMenuButton.vue
  src/components/VHeaderOld/VFilterButtonOld.vue
  src/components/VHeaderOld/VHeaderFilter.vue
  src/components/VHeaderOld/VHeaderMenu.vue
  src/components/VHeaderOld/VHeaderOld.vue
  src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue
  src/components/VHeaderOld/VSearchBar/VSearchButtonOld.vue
  src/components/VHeaderOld/VSearchBar/meta/VSearchBarOld.stories.mdx
  src/components/VHeaderOld/meta/VFilterButton.stories.mdx
  src/pages/index.vue
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#1844 Allow setting feature flags using query params
  src/middleware/middleware.ts
  src/stores/feature-flag.ts
  test/unit/specs/stores/feature-flag-store.spec.js
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#1848 Run Nuxt build and Playwright CI in parallel
  .github/workflows/ci.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1823 Reduce api token logging
  src/plugins/api-token.server.ts
Labels: 🚦 status: awaiting triage

#1821 Create locale chooser `VLanguage` and place in the footer
  nuxt.config.ts
  src/assets/icons/globe.svg
  src/components/VFooter/VFooter.vue
  src/components/VFourOhFour.vue
  src/components/VLanguageSelect/VLanguageSelect.vue
  src/components/VLanguageSelect/meta/VLanguageSelect.stories.mdx
  src/components/VSelectField/VSelectField.vue
  src/components/VSelectField/meta/VSelectField.stories.mdx
  src/layouts/default.vue
  src/locales/en.json
  src/locales/scripts/get-validated-locales.js
  test/locales/scripts/valid-locales.json
  test/storybook/visual-regression/v-language-select.spec.ts
  test/storybook/visual-regression/v-language-select.spec.ts-snapshots/vlanguageselect-default-linux.png
  test/storybook/visual-regression/v-select-field.spec.ts
  test/storybook/visual-regression/v-select-field.spec.ts-snapshots/vselectfield-default-linux.png
  test/storybook/visual-regression/v-select-field.spec.ts-snapshots/vselectfield-with-icon-linux.png
  test/storybook/visual-regression/v-select-field.spec.ts-snapshots/vselectfield-without-border-linux.png
  typings/nuxt__types/index.d.ts
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#1825 Add VHeaderInternal
  src/assets/icons/menu.svg
  src/components/VFooter/VFooter.vue
  src/components/VHeader/VHeaderInternal.vue
  src/components/VHeader/VHomeLink.vue
  src/components/VHeader/VPageLinks.vue
  src/components/VHeader/meta/VHeaderInternal.stories.mdx
  src/components/VIconButton/VIconButton.vue
  src/components/VModal/VModal.vue
  src/components/VModal/VModalContent.vue
  src/composables/use-pages.ts
  src/layouts/default.vue
  src/locales/en.json
  src/pages/about.vue
  test/locales/ar.json
  test/playwright/e2e/header-internal.spec.ts
  test/playwright/utils/navigation.ts
  test/storybook/visual-regression/v-header-internal.spec.ts
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-ltr-2xl-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-ltr-lg-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-ltr-md-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-ltr-xl-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-rtl-2xl-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-rtl-lg-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-rtl-md-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/desktop-header-internal-rtl-xl-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-ltr-sm-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-ltr-xs-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-modal-ltr-sm-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-modal-ltr-xs-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-modal-rtl-sm-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-modal-rtl-xs-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-rtl-sm-linux.png
  test/storybook/visual-regression/v-header-internal.spec.ts-snapshots/mobile-header-internal-rtl-xs-linux.png
  tsconfig.json
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#1842 Refactor SearchTypePopover desktop header
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VContentSwitcher/VSearchTypes.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VLogoLoader/VLogoLoader.vue
  src/layouts/default.vue
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#1860 Add search type button
  src/components/VButton.vue
  src/components/VContentSwitcher/VMobileMenuModal.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VContentSwitcher/meta/VSearchTypeButton.stories.mdx
  src/composables/use-search-type.ts
  test/storybook/playwright.config.ts
  test/storybook/visual-regression/v-search-type-button.spec.ts
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-at-rest-lg-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-hovered-lg-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-pressed-hovered-lg-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-pressed-lg-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-with-text-at-rest-xl-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-with-text-hovered-xl-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-with-text-pressed-hovered-xl-linux.png
  test/storybook/visual-regression/v-search-type-button.spec.ts-snapshots/v-search-type-button-with-text-pressed-xl-linux.png
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface
