Repository WordPress/openverse-frontend, pull requests merged in 2022-08, with the labels that each got.

#1599 Load locales in pre-commit if necessary
  .husky/pre-commit
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1590 Add TS to useWindowScroll
  src/composables/use-window-scroll.ts
  test/unit/.eslintrc.js
  test/unit/specs/composables/use-window-scroll.spec.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1569 Frontend tokens
  .env.template
  TESTING_GUIDELINES.md
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  src/data/api-service.ts
  src/data/media-provider-service.ts
  src/data/media-service.ts
  src/data/report-service.ts
  src/pages/search.vue
  src/plugins/api-token.server.ts
  src/plugins/focus-visible.client.ts
  src/stores/media/index.ts
  src/stores/media/related-media.ts
  src/stores/media/services.ts
  src/stores/media/single-result.ts
  src/stores/provider.ts
  src/utils/console.ts
  src/utils/node-env.ts
  test/unit/.eslintrc.js
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
  test/unit/specs/components/image-grid.spec.js
  test/unit/specs/components/related-images.spec.js
  test/unit/specs/components/v-filter-checklist.spec.js
  test/unit/specs/components/v-search-grid-filter.spec.js
  test/unit/specs/components/v-sources-table.spec.js
  test/unit/specs/pages/browse-page.spec.js
  test/unit/specs/plugins/api-token.server.spec.ts
  test/unit/specs/stores/active-media-store.spec.js
  test/unit/specs/stores/feature-flag-store.spec.js
  test/unit/specs/stores/media-store.spec.js
  test/unit/specs/stores/nav-store.spec.js
  test/unit/specs/stores/provider.spec.js
  test/unit/specs/stores/search-store.spec.js
  test/unit/specs/stores/single-result-store.spec.js
  test/unit/test-utils/api-service-mock.ts
  test/unit/test-utils/pinia.js
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1624 Ignore local only errors that do not matter
  src/utils/sentry-config.ts
Labels: 🟩 priority: low, 🧰 goal: internal improvement, ♿️ aspect: a11y

#1613 Text styles in no results page are incorrect #1588
  src/components/VErrorSection/VNoResults.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1626 Rename _size to layoutSize to remove underscore
  src/components/VAudioTrack/VAudioTrack.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1629 Check paginated versions during Rollback version check
  .github/workflows/rollback.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1640 Fix/e2e tests
  bin/playwright.sh
  test/playwright/e2e/all-results-keyboard.spec.ts
  test/playwright/e2e/attribution.spec.ts
  test/playwright/e2e/homepage.spec.ts
  test/playwright/e2e/image-detail.spec.ts
  test/playwright/e2e/migration-banner.spec.ts
  test/playwright/e2e/mobile-menu.spec.ts
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/e2e/search-query-client.spec.ts
  test/playwright/e2e/search-query-server.spec.ts
  test/playwright/e2e/search-types.spec.ts
  test/playwright/e2e/search.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xs-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-xs-linux.png
  test/tapes/response-494.json5
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1652 Make Renovate bot ignore forks and remove the SENTR_DSN
  .github/renovate.json
  src/utils/sentry-config.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1642 Fixes missing ar.json file.
  test/playwright/utils/navigation.ts
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1663 Updates handbook broken link
  README.md
Labels: 🚦 status: awaiting triage

#1672 Remove extraneous `--` from `lint:fix` script
  package.json
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#1643 Avoid pausing audio when is loading
  src/components/VAudioTrack/VPlayPause.vue
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1685 Revert "Avoid pausing audio when is loading"
  src/components/VAudioTrack/VPlayPause.vue
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1675 Remove unused composite action
  .github/actions/build/action.yml
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1644 Heading order & formating fixed
  src/pages/extension.vue
  src/pages/sources.vue
Labels: 🟨 priority: medium, 🌟 goal: addition, ♿️ aspect: a11y

#1693 Fix the visual regression test failures
  src/components/VContentPage.vue
  src/pages/extension.vue
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/meta-search-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/sources-rtl-xs-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-lg-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-md-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-sm-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-ltr-xs-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-lg-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-md-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-sm-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-xl-linux.png
  test/playwright/visual-regression/pages/sources.spec.ts-snapshots/sources-rtl-xs-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1664 Sentry package update
  package.json
  pnpm-lock.yaml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1651 Audio label fixed
  src/components/VAudioTrack/VWaveform.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1679 Update deployment actions to fix task definition registration
  .github/actions/production-frontend-deploy/action.yml
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1684 Add DEPLOYMENT.md
  DEPLOYMENT.md
Labels: 🟨 priority: medium, 📄 aspect: text, 🧰 goal: internal improvement

#1697 Fix sed usage
  .github/actions/production-frontend-deploy/action.yml
  .github/actions/staging-frontend-deploy/action.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1659 Correct heading order for single audio result pages
  src/components/VAudioDetails/VAudioDetails.vue
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VMediaInfo/VCopyLicense.vue
  src/components/VMediaInfo/VMediaLicense.vue
  src/components/VMediaInfo/VMediaReuse.vue
  test/playwright/visual-regression/components/media-reuse.spec.ts
  test/unit/specs/components/related-audios.spec.js
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#1678 Correct heading order for single IMAGE result page
  src/components/VImageDetails/VImageDetails.vue
  src/components/VImageDetails/VRelatedImages.vue
Labels: 🟨 priority: medium, ✨ goal: improvement, ♿️ aspect: a11y

#1621 Add `VSnackbar` component
  src/components/VContentLink/meta/VContentLink.stories.js
  src/components/VSnackbar.vue
  src/components/meta/VSnackbar.stories.mdx
  tsconfig.json
Labels: 🟧 priority: high, 🌟 goal: addition, 🕹 aspect: interface

#1682 Enable seeking for Jamendo tracks in blink browsers; remove message
  src/components/VAudioTrack/VWaveform.vue
  src/components/VAudioTrack/layouts/VRowLayout.vue
  src/composables/use-browser-detection.ts
  src/locales/en.json
  test/locales/ar.json
  test/locales/es.json
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1647 Replace Search result page `h` element with a `p` element
  src/components/VMetaSearch/VMetaSearchForm.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, ♿️ aspect: a11y

#1668 Add better concurrency settings for workflows
  .github/workflows/actionlint.yml
  .github/workflows/bundle_size.yml
  .github/workflows/generate_pot.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/ghcr.yml
  .github/workflows/label_new_pr.yml
  .github/workflows/rollback.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1653 Vendor in Reakit functions
  package.json
  pnpm-lock.yaml
  src/components/VItemGroup/VItemGroup.vue
  src/components/VSkipToContentContainer.vue
  src/composables/use-body-scroll-lock.ts
  src/composables/use-event-listener-outside.js
  src/composables/use-focus-on-blur.js
  src/composables/use-focus-on-hide.js
  src/composables/use-focus-on-show.js
  src/composables/use-hide-on-click-outside.js
  src/utils/a11y/is-native-tabbable.ts
  src/utils/dom/get-document.ts
  src/utils/reakit-utils/README.md
  src/utils/reakit-utils/dom.ts
  src/utils/reakit-utils/focus.ts
  test/unit/specs/components/v-popover.spec.js
  tsconfig.json
  typings/csstype/index.d.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1704 Update pinia and @pinia/nuxt
  package.json
  pnpm-lock.yaml
  test/tapes/detail/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8_close.json5
  test/tapes/related/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8_close.json5
  test/tapes/search_audio_q=honey_keep-alive.json5
  test/tapes/search_images_q=honey_keep-alive.json5
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement, dependencies

#1716 Use vue-portal for VTeleport
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VSidebarContent.vue
  src/components/VModal/VModalContent.vue
  src/components/VModal/VModalTarget.vue
  src/components/VModal/VSidebarTarget.vue
  src/components/VSkipToContentContainer.vue
  src/components/VTeleport/README.md
  src/components/VTeleport/VTeleport.vue
  src/components/VTeleport/VTeleportTarget.vue
  src/components/VTeleport/meta/targets.js
  src/layouts/default.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#1705 Update `throttle-debounce`
  package.json
  pnpm-lock.yaml
  src/composables/use-scroll.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1628 Convert active media to options store
  src/stores/active-media.ts
  test/unit/specs/stores/active-media-store.spec.js
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#1720 Add `minimum-change-threshold` to bundle size job and ignore language files
  .github/workflows/bundle_size.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1712 Doc improvement
  README.md
Labels: 🚦 status: awaiting triage

#1723 fixed warning for browserslist
  pnpm-lock.yaml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1645 Incorrect text styles in metadata information
  src/components/VAudioDetails/VAudioDetails.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1706 Use the specific tag for staging deployments
  .github/workflows/ghcr.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1690 Update Audio and Image's action button text
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/locales/en.json
  test/unit/specs/components/AudioTrack/v-full-layout.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#1727 Clean event listener on `use-hide-on-click-outside` composable
  src/composables/use-hide-on-click-outside.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1726 Updated variant name from `plain-dangerous` to `plain--avoid`
  src/components/VAudioTrack/VPlayPause.vue
  src/components/VButton.vue
  src/components/VTabs/VTab.vue
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1729 Fix typo in concurrency cancellation check
  .github/workflows/ghcr.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1686 Set maximum height to the popover to prevent cut-off on smaller screens
  src/components/VContentSwitcher/VSearchTypePopover.vue
  src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
  src/components/VPopover/VPopover.vue
  src/components/VPopover/VPopoverContent.types.js
  src/components/VPopover/VPopoverContent.vue
  src/composables/use-popover-content.js
  src/composables/use-popper.js
  src/composables/use-popper.ts
  src/composables/use-window-size.ts
  typings/csstype/index.d.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#1733 Add design issue template
  .github/ISSUE_TEMPLATE/design_changes.md
Labels: 🟧 priority: high, ✨ goal: improvement, 📄 aspect: text

#1744 Fix `VWaveform` story and silence mocked `$sentry` call logs
  src/components/VAudioTrack/meta/VWaveform.stories.mdx
  src/utils/sentry-config.ts
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#1747 Replace use-fetch-state with simpler implementation
  src/components/VAudioDetails/VRelatedAudio.vue
  src/components/VImageDetails/VRelatedImages.vue
  src/components/VImageGrid/VImageGrid.vue
  src/components/VLoadMore.vue
  src/components/VSearchGrid.vue
  src/composables/use-fetch-state.ts
  src/models/fetch-state.ts
  src/pages/search/search-page.types.ts
  src/stores/media/index.ts
  src/stores/media/related-media.ts
  src/stores/media/single-result.ts
  src/stores/provider.ts
  test/unit/specs/composables/use-fetch-state.spec.ts
  test/unit/specs/stores/media-store.spec.js
  test/unit/specs/stores/provider.spec.js
  test/unit/specs/stores/single-result-store.spec.js
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1749 Render filters sidebar clientside only (hotfix for #1748)
  src/components/VHeader/VHeaderFilter.vue
Labels: 🚦 status: awaiting triage

#1635 Update Vue to v2.7
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/components/VAudioTrack/VGlobalAudioTrack.vue
  src/components/VAudioTrack/VWaveform.vue
  src/components/VErrorSection/VErrorImage.vue
  src/composables/use-focus-on-show.js
  test/playwright/utils/breakpoints.ts
  test/playwright/utils/navigation.ts
  tsconfig.json
  typings/csstype/index.d.ts
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement, dependencies

#1751 Simplify Filters to fix the SSR problem
  package.json
  src/components/VHeader/VHeader.vue
  src/components/VHeader/VHeaderFilter.vue
  src/components/VHeader/VSidebarContent.vue
  src/composables/use-filter-sidebar-visibility.ts
  test/playwright/playwright.config.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/audio-results.spec.ts
  test/playwright/visual-regression/components/header.spec.ts
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-2xl-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-lg-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-md-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-sm-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-xl-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-ltr-xs-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-2xl-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-lg-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-md-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-sm-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-xl-linux.png
  test/playwright/visual-regression/components/header.spec.ts-snapshots/filters-open-rtl-xs-linux.png
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1755 Add external link icon to CTA
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/pages/image/_id.vue
  test/locales/ar.json
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
Labels: 🚦 status: awaiting triage

#1741 Switch to "get this [media]" for single result CTAs
  README.md
  src/components/VAudioTrack/layouts/VFullLayout.vue
  src/components/VContentSwitcher/VSearchTypeButton.vue
  src/components/VSkipToContentContainer.vue
  src/locales/en.json
  src/pages/image/_id.vue
  test/locales/ar.json
  test/playwright/playwright.config.ts
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-ltr-rich-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-html-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-plain-tab-xs-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-2xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-lg-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-md-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-sm-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xl-linux.png
  test/playwright/visual-regression/components/media-reuse.spec.ts-snapshots/media-reuse-rtl-rich-tab-xs-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#1745 Fix modal not hiding on escape
  src/components/VModal/VModalContent.vue
  test/unit/specs/components/v-modal.spec.js
Labels: 🟨 priority: medium, 🛠 goal: fix, ♿️ aspect: a11y

#1717 Remove PM2 from the Dockerfile and add curl for the healthcheck
  Dockerfile
  ecosystem.config.js
  nuxt.config.ts
  pnpm-lock.yaml
  src/server-middleware/healthcheck.js
  tsconfig.json
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#1734 Add info about env variables to deployment doc
  DEPLOYMENT.md
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#1750 Stop Global Audio player from playing loose audio
  src/components/VGlobalAudioSection/VGlobalAudioSection.vue
  test/playwright/e2e/global-audio.spec.ts
  test/tapes/related/audio/b502f915-adce-406b-ad87-9b17250331dd_keep-alive.json5
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#1761 Fix lint staged to match pnpm:fix order and settings
  .eslintrc.js
  .lintstagedrc
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#1746 Re-fetch single item if it was taken from search results or related media
  src/stores/media/index.ts
  src/stores/media/single-result.ts
  test/playwright/e2e/audio-detail.spec.ts
  test/playwright/e2e/report-media.spec.ts
  test/playwright/utils/navigation.ts
  test/proxy.js
  test/tapes/detail/audio/2e38ac1e-830c-4e9c-b13d-2c9a1ad53f95_keep-alive.json5
  test/tapes/detail/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365_keep-alive.json5
  test/tapes/detail/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8_keep-alive.json5
  test/tapes/detail/audio/7e063ee6-343f-48e4-a4a5-f436393730f6_close.json5
  test/tapes/detail/images/da5cb478-c093-4d62-b721-cda18797e3fb_keep-alive.json5
  test/tapes/detail/images/f9384235-b72e-4f1e-9b05-e1b116262a29_keep-alive.json5
  test/tapes/detail/images/feb91b13-422d-46fa-8ef4-cbf1e6ddee9b_keep-alive.json5
  test/tapes/related/audio/7e063ee6-343f-48e4-a4a5-f436393730f6_close.json5
  test/tapes/response-495.json5
  test/tapes/search/audio/q=honey_keep-alive.json5
  test/tapes/search/images/q=honey_keep-alive.json5
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
