Repository WordPress/openverse-frontend, pull requests merged in 2023-02, with the labels that each got.

#2078 Use a modal for external sources on mobile
  src/components/VButton.vue
  src/components/VExternalSearch/VExternalSearchForm.vue
  src/components/VExternalSearch/VExternalSourceList.vue
  src/components/VModal/VModalContent.vue
  src/components/VPopover/VPopoverContent.vue
  src/composables/use-dialog-control.ts
  src/types/button.ts
  src/types/modal.ts
  test/playwright/e2e/search-types-old.spec.ts
  test/playwright/e2e/search-types.spec.ts
  test/playwright/visual-regression/components/external-sources-section.spec.ts
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-ltr-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-ltr-png-xl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-rtl-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-all-sources-popover-rtl-png-xl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-ltr-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-ltr-png-xl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-rtl-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-audio-sources-popover-rtl-png-xl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-ltr-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-ltr-png-xl-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-rtl-png-sm-linux.png
  test/playwright/visual-regression/components/external-sources-section.spec.ts-snapshots/external-image-sources-popover-rtl-png-xl-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/dropdown-label-hovered-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/dropdown-label-pressed-hovered-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/dropdown-label-pressed-linux.png
  test/storybook/visual-regression/v-button.spec.ts-snapshots/dropdown-label-resting-linux.png
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#2123 Update deployment actions using new definitions
  .github/actions/production-deploy/action.yml
  .github/actions/staging-deploy/action.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#2115 Set layout height to 100dvh with fallback to 100vh
  src/components/VFourOhFour.vue
  src/components/VModal/VInputModal.vue
  src/components/VModal/VModalContent.vue
  src/layouts/default.vue
  src/pages/index.vue
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/pages/no-results.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#2142 Increase sidebar width by `20px` to accommodate a scrollbar
  src/styles/tailwind.css
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-ltr-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-filters-selected-rtl-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-ltr-linux.png
  test/playwright/visual-regression/components/filters-sidebar.spec.ts-snapshots/filters-sidebar-rtl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-page-rtl-lg-linux.png
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#2144 Increase horizontal padding in mobile search grid
  src/pages/search.vue
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-xs-linux.png
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#2093 Serve Prometheus metrics on a separate port; fix metrics development workflow
  nuxt.config.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#2121 Update eslint- and prettier- related dependencies
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#2104 Add Debounce to filter selection
  src/components/VFilters/VSearchGridFilter.vue
  test/playwright/e2e/search-navigation-old.spec.ts
  test/playwright/e2e/search-navigation.spec.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#2155 Fix the header scrolling
  src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
  src/layouts/content-layout.vue
  src/layouts/default.vue
  src/pages/about.vue
  src/pages/audio/_id/index.vue
  src/pages/external-sources.vue
  src/pages/feedback.vue
  src/pages/image/_id/index.vue
  src/pages/preferences.vue
  src/pages/privacy.vue
  src/pages/search-help.vue
  src/pages/search.vue
  src/pages/sources.vue
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-page-rtl-lg-linux.png
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#2120 Update babel-related dependencies
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#2154 Enable new header feature flag in production
  feat/feature-flags.json
Labels: 🟥 priority: critical, 🌟 goal: addition, 🕹 aspect: interface

#2157 Baseline SEO improvements
  nuxt.config.ts
  src/layouts/content-layout.vue
  src/layouts/default.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  src/pages/search/index.vue
  src/server-middleware/robots.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🕹 aspect: interface

#2101 Update search term when navigating with browser`s back and forward buttons
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VAllResultsGrid/VAudioCell.vue
  src/components/VAllResultsGrid/VImageCellSquare.vue
  src/components/VAudioTrack/VAudioTrack.vue
  src/components/VImageGrid/VImageCell.vue
  src/components/VImageGrid/VImageGrid.vue
  src/pages/audio/_id/index.vue
  src/pages/image/_id/index.vue
  src/pages/search/audio.vue
  test/playwright/e2e/all-results-keyboard.spec.ts
  test/playwright/e2e/search-navigation.spec.ts
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#2147 Tighten the condition for audio playback to continue across pages
  src/components/VAudioTrack/VAudioTrack.vue
  test/unit/specs/components/AudioTrack/v-audio-track.spec.js
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#2158 Minify homepage images
  src/assets/homepage_images/olympics/1.png
  src/assets/homepage_images/olympics/10.png
  src/assets/homepage_images/olympics/11.png
  src/assets/homepage_images/olympics/12.png
  src/assets/homepage_images/olympics/13.png
  src/assets/homepage_images/olympics/14.png
  src/assets/homepage_images/olympics/15.png
  src/assets/homepage_images/olympics/2.png
  src/assets/homepage_images/olympics/3.png
  src/assets/homepage_images/olympics/4.png
  src/assets/homepage_images/olympics/5.png
  src/assets/homepage_images/olympics/6.png
  src/assets/homepage_images/olympics/7.png
  src/assets/homepage_images/olympics/8.png
  src/assets/homepage_images/olympics/9.png
  src/assets/homepage_images/pottery/1.png
  src/assets/homepage_images/pottery/10.png
  src/assets/homepage_images/pottery/11.png
  src/assets/homepage_images/pottery/12.png
  src/assets/homepage_images/pottery/13.png
  src/assets/homepage_images/pottery/14.png
  src/assets/homepage_images/pottery/15.png
  src/assets/homepage_images/pottery/2.png
  src/assets/homepage_images/pottery/3.png
  src/assets/homepage_images/pottery/4.png
  src/assets/homepage_images/pottery/5.png
  src/assets/homepage_images/pottery/6.png
  src/assets/homepage_images/pottery/7.png
  src/assets/homepage_images/pottery/8.png
  src/assets/homepage_images/pottery/9.png
  src/assets/homepage_images/universe/1.png
  src/assets/homepage_images/universe/10.png
  src/assets/homepage_images/universe/11.png
  src/assets/homepage_images/universe/12.png
  src/assets/homepage_images/universe/13.png
  src/assets/homepage_images/universe/14.png
  src/assets/homepage_images/universe/15.png
  src/assets/homepage_images/universe/2.png
  src/assets/homepage_images/universe/3.png
  src/assets/homepage_images/universe/4.png
  src/assets/homepage_images/universe/5.png
  src/assets/homepage_images/universe/6.png
  src/assets/homepage_images/universe/7.png
  src/assets/homepage_images/universe/8.png
  src/assets/homepage_images/universe/9.png
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#2161 Ensure the lineage is traced correctly
  src/locales/scripts/read-i18n.js
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#2165 Group localized URLs of the same page in the sitemap
  nuxt.config.ts
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#2109 Extract Prometheus module
  nuxt.config.ts
  src/modules/prometheus.ts
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#2149 Remove ring offset to reduce ring thickness
  src/components/VFilters/VSearchGridFilter.vue
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#2166 Update URL in opensearch.xml
  src/static/opensearch.xml
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface

#2169 Update common's size estimate to 2.5 billion
  src/locales/scripts/en.json5
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/about-ltr-xs-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#2172 Make translations more reliably present in all environments
  package.json
  pnpm-lock.yaml
  src/locales/scripts/axios.js
  src/locales/scripts/get-translations.js
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#2177 Use h1 for the main heading on the homepage
  src/components/VHomepageContent.vue
Labels: 🟧 priority: high, ✨ goal: improvement, ♿️ aspect: a11y

#2184 Reduce GlotPress limit further to ensure all languages
  src/locales/scripts/axios.js
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#2134 Fix the Search Help (Syntax Guide) links
  src/locales/scripts/en.json5
  src/pages/search-help.vue
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-md-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-sm-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-help-rtl-xs-linux.png
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#2187 Use aria-label for WordPress affiliation link
  src/components/VHeader/VWordPressLink.vue
Labels: 🟨 priority: medium, 🛠 goal: fix, ♿️ aspect: a11y

#2185 Move the sidebar in the DOM order
  src/components/VAllResultsGrid/VAllResultsGrid.vue
  src/components/VExternalSearch/VExternalSearchForm.vue
  src/components/VFilters/VSearchGridFilter.vue
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VImageGrid/VImageGrid.vue
  src/composables/use-focus-filters.ts
  src/layouts/content-layout.vue
  src/pages/search.vue
  src/pages/search/audio.vue
  src/pages/search/image.vue
  test/playwright/e2e/filters-sidebar-keyboard.spec.ts
  test/playwright/e2e/header-internal.spec.ts
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#2178 Add "skip to content link" to the Single result pages
  src/components/VSkipToContentContainer.vue
  src/layouts/default.vue
  src/pages/audio/_id/index.vue
  src/pages/image/_id/index.vue
  src/pages/image/_id/report.vue
  src/pages/index.vue
Labels: 🟧 priority: high, ✨ goal: improvement, ♿️ aspect: a11y

#2192 Simplify `get-translations.js` and add error handling and fallbacks
  src/locales/scripts/bulk-download.js
  src/locales/scripts/get-translations.js
  src/locales/scripts/separate-download.js
  src/locales/scripts/utils.js
Labels: 🟧 priority: high, ✨ goal: improvement, 🤖 aspect: dx

#2180 Add "skip to content" links to the homepage and the 404 page; fix footer role
  src/components/VFourOhFour.vue
  src/components/VHomepageContent.vue
  src/layouts/default.vue
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-ltr-xs-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-lg-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xl-linux.png
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/non-existent-rtl-xs-linux.png
Labels: 🟧 priority: high, ✨ goal: improvement, ♿️ aspect: a11y

#2191 Add a directive for translators to not translate Netherlands
  src/locales/scripts/en.json5
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#2188 Download translations in bulk to prevent GlotPress throttling
  .github/workflows/ghcr.yml
  .gitignore
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/locales/scripts/bulk-download.js
  src/locales/scripts/get-translations.js
  src/locales/scripts/locales-list.json
  src/locales/scripts/separate-download.js
  src/locales/scripts/utils.js
Labels: 🟧 priority: high, 🛠 goal: fix, ♿️ aspect: a11y

#2196 Monorepo archive notice
  README.md
Labels: 🟧 priority: high, 🌟 goal: addition, 🤖 aspect: dx
