Repository WordPress/openverse-frontend, pull requests merged in 2023-01, with the labels that each got.

#2046 Update the search term when users click the back button; extract useSearch
  src/components/VHeader/VHeaderDesktop.vue
  src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
  src/components/VHeaderOld/VHeaderMenu.vue
  src/components/VHeaderOld/VHeaderOld.vue
  src/composables/use-i18n-utilities.ts
  src/composables/use-search.ts
  src/pages/search.vue
  src/stores/search.ts
  test/playwright/e2e/search-navigation.spec.ts
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-ltr-xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-lg-linux.png
  test/playwright/visual-regression/pages/homepage.spec.ts-snapshots/index-rtl-xl-linux.png
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#2086 Add new deployment action for staging.openverse.org
  .github/actions/staging-deploy/action.yml
  .github/workflows/ghcr.yml
  .github/workflows/rollback.yml
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#2088 Remove old staging deployments
  .github/actions/staging-frontend-deploy/action.yml
  .github/workflows/ghcr.yml
  .github/workflows/rollback.yml
  DEPLOYMENT.md
  TESTING_GUIDELINES.md
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1998 Component scaffolding generator
  .pre-commit-config.yaml
  .prettierignore
  .remake/component-storybook-test/remake-fileName.spec.ts
  .remake/component-unit-test/remake-fileName.spec.js
  .remake/component/remake-name/remake-name.vue
  .remake/story/remake-name.stories.mdx
  README.md
  bin/add-entry-to-tsconfig.js
  bin/create-component.sh
  jest.config.js
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#2098 Reformat of how to create a component section in the main readme file
  README.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#2102 Enable new header in staging
  feat/feature-flags.json
  test/playwright/e2e/homepage.spec.ts
  test/playwright/e2e/migration-banner.spec.ts
  test/playwright/e2e/mobile-menu-old.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/components/audio-results-old.spec.ts
  test/playwright/visual-regression/components/header-old.spec.ts
  test/playwright/visual-regression/pages/homepage-old.spec.ts
  test/playwright/visual-regression/pages/pages-with-old-header.spec.ts
  test/unit/specs/stores/ui-store.spec.js
Labels: 🟧 priority: high, 🕹 aspect: interface, 🧰 goal: internal improvement

#2103 Set the new_header flag to enabled
  feat/feature-flags.json
Labels: 🚦 status: awaiting triage

#2090 Image reporting view
  src/components/VContentReport/VContentReportForm.vue
  src/components/VContentReport/VContentReportPopover.vue
  src/composables/use-match-routes.ts
  src/locales/scripts/en.json5
  src/pages/audio/_id/index.vue
  src/pages/image/_id/index.vue
  src/pages/image/_id/report.vue
Labels: 🟥 priority: critical, 🌟 goal: addition, 🕹 aspect: interface

#2095 Update deployment actions for production.openverse.org
  .github/actions/production-deploy/action.yml
  .github/workflows/ghcr.yml
  .github/workflows/rollback.yml
  DEPLOYMENT.md
Labels: 🟧 priority: high, ✨ goal: improvement, 🤖 aspect: dx

#2099 add hover state for play-pause button
  src/components/VAudioTrack/layouts/VBoxLayout.vue
  test/playwright/e2e/homepage.spec.ts
  test/playwright/e2e/translation-banner.spec.ts
  test/playwright/utils/navigation.ts
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface

#2077 External sources on no results page
  src/components/VErrorSection/VNoResults.vue
  src/components/VExternalSearch/VExternalSearchForm.vue
  src/components/VExternalSearch/VExternalSourceList.vue
  src/components/VSearchGrid.vue
  src/components/VSearchResultsTitle.vue
  src/constants/media.ts
  src/types/external-source.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/pages/no-results.spec.ts
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-all-rtl-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-audio-rtl-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-ltr-xs-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-2xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-lg-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-md-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-sm-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-xl-linux.png
  test/playwright/visual-regression/pages/no-results.spec.ts-snapshots/no-results-image-rtl-xs-linux.png
  tsconfig.json
Labels: 🟨 priority: medium, ✨ goal: improvement, 🕹 aspect: interface

#2108 Use correct color for different routes in the default layout
  src/composables/use-match-routes.ts
  src/layouts/default.vue
  test/playwright/e2e/load-more.spec.ts
  test/playwright/playwright.config.ts
  test/playwright/utils/navigation.ts
  test/playwright/visual-regression/pages/pages.spec.ts
  test/playwright/visual-regression/pages/pages.spec.ts-snapshots/search-page-rtl-lg-linux.png
  test/tapes/response-622.json5
  test/tapes/search/audio/q=birds&license_type=commercial&peaks=true_keep-alive.json5
  test/tapes/search/images/q=birds&license_type=commercial_keep-alive.json5
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface

#2106 Fix internal header menu
  src/components/VHeader/VHeaderInternal.vue
  src/components/VModal/VInputModal.vue
  src/components/VModal/VModal.vue
  src/components/VModal/VModalContent.vue
  src/composables/use-dialog-content.ts
  src/composables/use-dialog-control.ts
  src/composables/use-focus-on-show.ts
  src/composables/use-focus-trap.ts
  test/playwright/README.md
  test/playwright/e2e/header-internal.spec.ts
  test/playwright/utils/navigation.ts
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface
